import { GRAN_TIERRA_MONTHLY_DATA, type GranTierraMonthKey } from "./granTierraMonthly";
import { MAINTENANCE_PLANS } from "./maintenancePlansData";
import {
  computeMphi,
  evaluationFromMphi,
  healthBandFromMphi,
  type CriticalityLevel,
  type EquipmentType,
  type ExpectedBenefits,
  type MaintenanceOptimizationPlan,
  type MaintenanceRecommendation,
  type MaintenanceStrategy,
  type OptimizationStatus,
} from "./maintenanceOptimizationTypes";

function normEq(s: string) {
  return s.toUpperCase().replace(/[^A-Z0-9]/g, "");
}

function rec(
  planId: string,
  n: number,
  recommendation: string,
  priority: MaintenanceRecommendation["priority"],
  expectedBenefit: string,
  estimatedSavingsPct: number,
  implementationCost: number,
  responsible: string,
  status: MaintenanceRecommendation["status"],
  autoGenerated: boolean,
  trigger?: string,
): MaintenanceRecommendation {
  return {
    id: `${planId}-R${n}`,
    planId,
    recommendation,
    priority,
    expectedBenefit,
    estimatedSavingsPct,
    implementationCost,
    responsible,
    status,
    createdAt: MAINTENANCE_PLANS.extractedAt,
    autoGenerated,
    trigger,
  };
}

function modelMeta(model: string): {
  equipmentType: EquipmentType;
  manufacturer: string;
  criticalityBase: CriticalityLevel;
} {
  const m = model.toUpperCase();
  if (/J320|J420/.test(m)) {
    return { equipmentType: "Motor", manufacturer: "Jenbacher / INNIO", criticalityBase: "Alta" };
  }
  if (/600GFT|JINAN/.test(m)) {
    return { equipmentType: "Motor", manufacturer: "Jinan / gas", criticalityBase: "Alta" };
  }
  if (/KTA/.test(m)) {
    return { equipmentType: "Motor", manufacturer: "Cummins", criticalityBase: "Media" };
  }
  if (/SWG/.test(m)) {
    return { equipmentType: "Generador", manufacturer: "Switchgear", criticalityBase: "Alta" };
  }
  if (/FILTRO|COALESCENTE|MRU|MQT|CYC/.test(m) || /FILTRO|MRU|MQT|CYC/.test(m)) {
    return { equipmentType: "MRU", manufacturer: "Tratamiento gas", criticalityBase: "Muy Alta" };
  }
  return { equipmentType: "Motor", manufacturer: model || "Flota Putumayo", criticalityBase: "Media" };
}

function raiseCriticality(base: CriticalityLevel, steps: number): CriticalityLevel {
  const order: CriticalityLevel[] = ["Baja", "Media", "Alta", "Muy Alta"];
  const idx = Math.min(order.length - 1, Math.max(0, order.indexOf(base) + steps));
  return order[idx];
}

function parseMtbf(label: string | null | undefined): number | null {
  if (!label || /sin/i.test(label)) return null;
  const n = Number(String(label).replace(/,/g, "").trim());
  return Number.isFinite(n) ? n : null;
}

type EqAgg = {
  equipment: string;
  programmed: number;
  executed: number;
  pending: number;
  postponed: number;
  manHours: number;
  mtoHours: number;
  notes: string[];
};

function aggregateEquipment(monthKey: string | null): Map<string, EqAgg> {
  const map = new Map<string, EqAgg>();

  const bump = (name: string): EqAgg => {
    const key = normEq(name);
    const existing = map.get(key);
    if (existing) return existing;
    const created: EqAgg = {
      equipment: name.trim(),
      programmed: 0,
      executed: 0,
      pending: 0,
      postponed: 0,
      manHours: 0,
      mtoHours: 0,
      notes: [],
    };
    map.set(key, created);
    return created;
  };

  for (const e of MAINTENANCE_PLANS.executions) {
    if (monthKey && e.monthKey && e.monthKey !== monthKey) continue;
    if (!e.programmed) continue;
    const parts = e.equipment.split(/[,;/]+/).map((s) => s.trim()).filter(Boolean);
    for (const part of parts) {
      const row = bump(part);
      row.programmed += 1;
      if (e.status === "ejecutado") row.executed += 1;
      if (e.status === "pendiente") row.pending += 1;
      const note = (e.notes ?? "").toLowerCase();
      if (/posterg|no cumple|stand\s*by|horas de (operaci|mto|manten)/i.test(note)) {
        row.postponed += 1;
      }
      if (e.notes) row.notes.push(e.notes);
      row.manHours += e.plannedManHours || 0;
    }
  }

  for (const s of MAINTENANCE_PLANS.calendarSlots) {
    if (monthKey && s.monthKey && s.monthKey !== monthKey) continue;
    if (s.isRun) continue;
    const row = bump(s.equipment);
    row.mtoHours += s.hoursMto ?? 0;
    row.manHours += s.manHours ?? 0;
  }

  return map;
}

function findAgg(map: Map<string, EqAgg>, equipment: string): EqAgg | null {
  const exact = map.get(normEq(equipment));
  if (exact) return exact;
  const target = normEq(equipment);
  for (const [key, val] of map) {
    if (key.includes(target) || target.includes(key)) return val;
  }
  return null;
}

/**
 * Portafolio MSO alimentado por la sábana Putumayo + indicadores GTE del mes (si existen).
 * No inventa OT: evalúa efectividad del plan vs ejecución real.
 */
export function buildSabanaMaintenanceOptimization(month: string): MaintenanceOptimizationPlan[] {
  const monthKey = month === "YTD2026" ? null : month;
  const aggs = aggregateEquipment(monthKey);
  const gteSnap =
    monthKey && GRAN_TIERRA_MONTHLY_DATA[monthKey as GranTierraMonthKey]
      ? GRAN_TIERRA_MONTHLY_DATA[monthKey as GranTierraMonthKey]
      : GRAN_TIERRA_MONTHLY_DATA.Jun;

  const gteByUnit = new Map(
    (gteSnap?.machineIndicators ?? [])
      .filter((m) => m.unidad !== "SISTEMA N")
      .map((m) => [normEq(m.unidad), m]),
  );

  const plans: MaintenanceOptimizationPlan[] = [];

  MAINTENANCE_PLANS.catalog.forEach((cat, idx) => {
    const id = `MSO-${String(idx + 1).padStart(3, "0")}`;
    const agg = findAgg(aggs, cat.equipment);
    const gte = gteByUnit.get(normEq(cat.equipment)) ?? null;
    const meta = modelMeta(cat.model);

    const programmed = agg?.programmed ?? 0;
    const executed = agg?.executed ?? 0;
    const pending = agg?.pending ?? 0;
    const postponed = agg?.postponed ?? 0;
    const compliance = programmed > 0 ? executed / programmed : 1;
    const postponeRate = programmed > 0 ? postponed / programmed : 0;

    const failures = gte?.fallas ?? (postponeRate > 0.5 ? Math.round(postponeRate * 3) : 0);
    const availabilityPct = gte?.disponibilidadPct ?? Math.max(90, 100 - (1 - compliance) * 8);
    const mtbfHours = parseMtbf(gte?.mtbfLabel) ?? (failures > 0 ? null : cat.periodicityHrs);
    const mttrHours = gte?.mttrHours ?? null;

    let critSteps = 0;
    if (compliance < 0.4 || postponeRate > 0.6) critSteps += 1;
    if (failures >= 2) critSteps += 1;
    if (/FILTRO|MRU|SWG/i.test(cat.equipment) || /FILTRO|MRU/i.test(cat.model)) critSteps += 1;
    const criticality = raiseCriticality(meta.criticalityBase, critSteps);

    const currentFrequency = `Cada ${cat.periodicityHrs.toLocaleString("es-CO")} h operación`;
    let recommendedStrategy: MaintenanceStrategy = "Preventivo";
    let recommendedFrequency = currentFrequency;
    let optimizationStatus: OptimizationStatus = "Pendiente análisis";
    let expectedBenefit = "Mantener plan alineado a horómetro";
    const benefits: ExpectedBenefits = {
      mtbfPct: 5,
      availabilityPct: 0.2,
      mttrPct: -3,
      costPct: -2,
      failuresPct: -8,
    };

    const recommendations: MaintenanceRecommendation[] = [];
    let n = 0;

    if (postponeRate >= 0.45 || compliance < 0.55) {
      recommendedStrategy = "Basado en Condición";
      recommendedFrequency = `Por horómetro (≥${cat.periodicityHrs} h) + ventana de oportunidad`;
      optimizationStatus = "Requiere optimización";
      expectedBenefit = "Reducir aplazos y ejecutar cuando el equipo cumpla horas reales";
      benefits.mtbfPct = 12;
      benefits.availabilityPct = 0.6;
      benefits.costPct = -8;
      benefits.failuresPct = -20;
      recommendations.push(
        rec(
          id,
          ++n,
          "Priorizar programación por horómetro frente a calendario fijo",
          "Crítica",
          "Cumplimiento de plan +25%",
          8,
          0,
          "Planeación MTO",
          "Abierta",
          true,
          `Aplazos ${(postponeRate * 100).toFixed(0)}% · cumplimiento ${(compliance * 100).toFixed(0)}%`,
        ),
      );
      recommendations.push(
        rec(
          id,
          ++n,
          "Usar paradas / standby como ventana de oportunidad controlada",
          "Alta",
          "Menos reprogramaciones",
          5,
          500,
          "Operación",
          "Abierta",
          true,
          "Notas: postergado por horas / standby",
        ),
      );
    } else if (compliance >= 0.85 && failures === 0) {
      recommendedStrategy = "Preventivo";
      if (cat.periodicityHrs <= 350) {
        recommendedFrequency = `Cada ${Math.round(cat.periodicityHrs * 1.15)} h (optimizar intervalo)`;
        benefits.costPct = -10;
        expectedBenefit = "Reducir sobre-mantenimiento sin degradar confiabilidad";
        recommendations.push(
          rec(
            id,
            ++n,
            `Evaluar extensión controlada del intervalo ${cat.periodicityHrs} h`,
            "Media",
            "Costo -10%",
            10,
            0,
            "Confiabilidad",
            "Abierta",
            true,
            "Alto cumplimiento + sin fallas GTE",
          ),
        );
      } else {
        recommendedFrequency = currentFrequency;
        expectedBenefit = "Plan efectivo: sostener intervalo actual";
      }
      optimizationStatus = "Validado";
      recommendations.push(
        rec(
          id,
          ++n,
          "Mantener registro de horómetro último MTO / actual en sábana",
          "Baja",
          "Trazabilidad",
          1,
          0,
          "Planeación MTO",
          "Implementada",
          false,
        ),
      );
    } else if (failures >= 2) {
      recommendedStrategy = "Predictivo";
      recommendedFrequency = `Cada ${Math.max(250, Math.round(cat.periodicityHrs * 0.75))} h + inspección por condición`;
      optimizationStatus = "Requiere optimización";
      expectedBenefit = "Acortar intervalo y agregar predictivo ante reincidencia";
      benefits.mtbfPct = 18;
      benefits.failuresPct = -30;
      benefits.availabilityPct = 0.8;
      recommendations.push(
        rec(
          id,
          ++n,
          `Acortar preventivo ${cat.periodicityHrs} h → ${Math.max(250, Math.round(cat.periodicityHrs * 0.75))} h`,
          "Alta",
          "Fallas -30%",
          4,
          2000,
          "Confiabilidad",
          "Abierta",
          true,
          `≥${failures} fallas en informe GTE`,
        ),
      );
      recommendations.push(
        rec(
          id,
          ++n,
          "Agregar inspección termográfica / condición en próximo PM",
          "Alta",
          "Detección temprana",
          3,
          1500,
          "Predictivo",
          "Abierta",
          true,
        ),
      );
    } else {
      recommendedStrategy = cat.periodicityHrs >= 1000 ? "Basado en Condición" : "Preventivo";
      recommendedFrequency =
        cat.periodicityHrs >= 1000
          ? `Cada ${cat.periodicityHrs} h + chequeo por condición`
          : currentFrequency;
      optimizationStatus = pending > executed ? "En aprobación" : "Pendiente análisis";
      expectedBenefit = "Alinear ejecución al plan de sábana";
      recommendations.push(
        rec(
          id,
          ++n,
          "Cerrar backlog de mantenimientos pendientes del mes",
          "Media",
          "Cumplimiento del cronograma",
          3,
          0,
          "Planeación MTO",
          "Abierta",
          true,
          `${pending} pendientes / ${programmed} programados`,
        ),
      );
    }

    if (/J320|J420/i.test(cat.model) && cat.periodicityHrs >= 1000 && compliance < 0.7) {
      recommendations.push(
        rec(
          id,
          ++n,
          "Revisar capacidad de cuadrilla vs densidad de PM Jenbacher 1000 h",
          "Media",
          "Menos colisiones de agenda",
          4,
          0,
          "Planeación MTO",
          "Abierta",
          true,
        ),
      );
    }

    const impactIndex = Number(
      (
        (1 - compliance) * 8 +
        postponeRate * 6 +
        failures * 1.4 +
        (criticality === "Muy Alta" ? 1.5 : criticality === "Alta" ? 0.8 : 0)
      ).toFixed(1),
    );

    const operatingHours = Math.max(
      agg?.mtoHours ?? 0,
      gte ? Math.round((availabilityPct / 100) * 720) : cat.periodicityHrs,
    );

    const mphi = computeMphi({
      criticality,
      availabilityPct,
      failures,
      mtbfHours,
      mttrHours,
      impactIndex,
    });

    const noteHints = (agg?.notes ?? [])
      .filter((n, i, arr) => arr.indexOf(n) === i)
      .slice(0, 3);

    const justification = [
      `Sábana Putumayo${monthKey ? ` · ${monthKey}` : " · YTD"}: ${programmed} PM programados, ${executed} ejecutados (${(compliance * 100).toFixed(0)}%), ${pending} pendientes, ${postponed} con aplazamiento/horas.`,
      gte
        ? `GTE ${gteSnap.label}: disp. ${availabilityPct.toFixed(2)}%, fallas ${gte.fallas}, MTBF ${gte.mtbfLabel}.`
        : "Sin fila GTE de indicador para esta unidad en el mes; se usa solo evidencia de sábana.",
      `Periodicidad catálogo: ${cat.periodicityHrs} h · esfuerzo típico ${cat.hoursMto} h MTO / ${cat.manHours} H-H.`,
    ].join(" ");

    plans.push({
      id,
      assetId: cat.equipment,
      assetName: cat.equipment,
      equipmentType: meta.equipmentType,
      manufacturer: meta.manufacturer,
      criticality,
      currentStrategy: "Preventivo",
      currentFrequency,
      recommendedStrategy,
      recommendedFrequency,
      optimizationStatus,
      justification,
      mphi,
      healthBand: healthBandFromMphi(mphi),
      evaluation: evaluationFromMphi(mphi),
      expectedBenefit,
      benefits,
      operatingHours,
      availabilityPct,
      mtbfHours,
      mttrHours,
      failures,
      maintenanceCostUsd: Math.round(programmed * cat.manHours * 45 + (1 - compliance) * 4000),
      outageHours: Math.round((agg?.mtoHours ?? 0) * 0.15),
      impactIndex,
      linkedRcaIds: [],
      linkedPlanIds: [],
      linkedEventHints: noteHints.length
        ? noteHints
        : [`Cumplimiento sábana ${(compliance * 100).toFixed(0)}%`],
      recommendations,
      createdAt: MAINTENANCE_PLANS.extractedAt,
      updatedAt: MAINTENANCE_PLANS.extractedAt,
    });
  });

  return plans.sort((a, b) => a.mphi - b.mphi || b.impactIndex - a.impactIndex);
}

export {
  portfolioKpis,
  strategyMix,
  topOpportunities,
} from "./gteJuneMaintenanceOptimization";
