import type { ReportDataset } from "../types";

export const copowerInternoReport: ReportDataset = {
  title: "Reporte Interno CoPower",
  subtitle: "Sin datos cargados actualmente. Este espacio queda reservado para el reporte interno de CoPower.",
  kpiData: [
    { month: "Ene", availability: 0, reliability: 0, maintainability: 0, generationMwh: 0, operationalLossesMwh: 0, contractualCompliance: 0 },
    { month: "Feb", availability: 0, reliability: 0, maintainability: 0, generationMwh: 0, operationalLossesMwh: 0, contractualCompliance: 0 },
    { month: "Mar", availability: 0, reliability: 0, maintainability: 0, generationMwh: 0, operationalLossesMwh: 0, contractualCompliance: 0 },
    { month: "Abr", availability: 0, reliability: 0, maintainability: 0, generationMwh: 0, operationalLossesMwh: 0, contractualCompliance: 0 },
    { month: "May", availability: 0, reliability: 0, maintainability: 0, generationMwh: 0, operationalLossesMwh: 0, contractualCompliance: 0 },
    { month: "Jun", availability: 0, reliability: 0, maintainability: 0, generationMwh: 0, operationalLossesMwh: 0, contractualCompliance: 0 },
  ],
  kpiTargets: {
    availability: 0,
    reliability: 0,
    maintainability: 0,
    generationMwh: 0,
    operationalLossesMwh: 0,
    contractualCompliance: 0,
  },
  badActors: [],
  rca: [
    { status: "Pendiente", value: 0, color: "#fb7185" },
    { status: "En curso", value: 0, color: "#f59e0b" },
    { status: "Cerrado", value: 0, color: "#22c55e" },
  ],
  maintenancePlan: [],
  actionPlan: [],
  summary: {
    copowerFailures: 0,
    totalEvents: 0,
    mtbfHours: 0,
    mttrHours: 0,
    actionsOverdue: 0,
    rcaPending: 0,
    hoursOperated: 0,
    hoursStandby: 0,
    hoursPreventive: 0,
    hoursCorrective: 0,
    hoursFailureCopower: 0,
    hoursFailureClient: 0,
    energyGasKwh: 0,
    energyDieselKwh: 0,
  },
  reliabilityTrend: [
    { month: "Ene", availability: 0, reliability: 0, mtbfHours: 0, mttrHours: 0 },
    { month: "Feb", availability: 0, reliability: 0, mtbfHours: 0, mttrHours: 0 },
    { month: "Mar", availability: 0, reliability: 0, mtbfHours: 0, mttrHours: 0 },
    { month: "Abr", availability: 0, reliability: 0, mtbfHours: 0, mttrHours: 0 },
    { month: "May", availability: 0, reliability: 0, mtbfHours: 0, mttrHours: 0 },
    { month: "Jun", availability: 0, reliability: 0, mtbfHours: 0, mttrHours: 0 },
  ],
  causePareto: [],
  generationByAsset: [],
  generationByEquipment: [],
  totalGenerationKwh: 0,
  eventLog: [],
  machineIndicators: [],
};
