/** Tipos del módulo Tendencias de Degradación y Riesgos (APM / rule-based). */

export type CriticalityLevel = "Muy Alta" | "Alta" | "Media" | "Baja";

export type HealthBand =
  | "Excelente"
  | "Bueno"
  | "Aceptable"
  | "En observación"
  | "Crítico";

export type DegradationLevel =
  | "Sin degradación"
  | "Leve"
  | "Moderada"
  | "Severa"
  | "Crítica";

export type RiskLevel = "Bajo" | "Medio" | "Alto" | "Crítico";

export type TrendDirection = "creciente" | "estable" | "decreciente";

export type AssetHealthStatus =
  | "Saludable"
  | "En observación"
  | "Degradación"
  | "Riesgo alto"
  | "Intervención"
  | "Recuperación";

export type RiskAssessmentStatus = "Abierta" | "En curso" | "Mitigada" | "Cerrada";

export type MonthlyPoint = {
  month: string;
  availabilityPct: number;
  mtbfHours: number | null;
  mttrHours: number;
  failures: number;
  operatingHours: number;
  impactIndex: number;
};

export type RiskAssessment = {
  id: string;
  assetHealthId: string;
  hazard: string;
  cause: string;
  consequence: string;
  probability: number;
  impact: number;
  risk: number;
  riskLevel: RiskLevel;
  recommendation: string;
  priority: "Crítica" | "Alta" | "Media" | "Baja";
  status: RiskAssessmentStatus;
  createdAt: string;
  autoGenerated: boolean;
};

export type AutoRecommendation = {
  id: string;
  trigger: string;
  recommendation: string;
  priority: "Crítica" | "Alta" | "Media" | "Baja";
};

export type AssetHealth = {
  id: string;
  assetId: string;
  assetName: string;
  field: string;
  criticality: CriticalityLevel;
  healthIndex: number;
  healthBand: HealthBand;
  degradationLevel: DegradationLevel;
  riskLevel: RiskLevel;
  probability: number;
  impact: number;
  riskScore: number;
  status: AssetHealthStatus;
  trend: TrendDirection;
  availabilityTrend: TrendDirection;
  mtbfTrend: TrendDirection;
  mttrTrend: TrendDirection;
  failuresTrend: TrendDirection;
  lastEvaluation: string;
  series: MonthlyPoint[];
  recommendations: AutoRecommendation[];
  assessments: RiskAssessment[];
  linkedRcaIds: string[];
  linkedPlanIds: string[];
  linkedMsoIds: string[];
  alerts: string[];
  createdAt: string;
  updatedAt: string;
};

export const CRITICALITY_COLOR: Record<CriticalityLevel, string> = {
  "Muy Alta": "#ef4444",
  Alta: "#f97316",
  Media: "#3b82f6",
  Baja: "#64748b",
};

export const HEALTH_BAND_COLOR: Record<HealthBand, string> = {
  Excelente: "#15803d",
  Bueno: "#16a34a",
  Aceptable: "#ca8a04",
  "En observación": "#ea580c",
  Crítico: "#dc2626",
};

export const DEGRADATION_COLOR: Record<DegradationLevel, string> = {
  "Sin degradación": "#15803d",
  Leve: "#65a30d",
  Moderada: "#ca8a04",
  Severa: "#ea580c",
  Crítica: "#dc2626",
};

export const RISK_LEVEL_COLOR: Record<RiskLevel, string> = {
  Bajo: "#15803d",
  Medio: "#ca8a04",
  Alto: "#ea580c",
  Crítico: "#dc2626",
};

export const TREND_LABEL: Record<TrendDirection, string> = {
  creciente: "Creciente",
  estable: "Estable",
  decreciente: "Decreciente",
};

export function healthBandFromIndex(hi: number): HealthBand {
  if (hi >= 90) return "Excelente";
  if (hi >= 80) return "Bueno";
  if (hi >= 70) return "Aceptable";
  if (hi >= 60) return "En observación";
  return "Crítico";
}

export function riskLevelFromScore(score: number): RiskLevel {
  if (score >= 16) return "Crítico";
  if (score >= 10) return "Alto";
  if (score >= 5) return "Medio";
  return "Bajo";
}

export function degradationFromHealth(hi: number, trend: TrendDirection): DegradationLevel {
  if (hi >= 90 && trend !== "decreciente") return "Sin degradación";
  if (hi >= 80) return trend === "decreciente" ? "Leve" : "Sin degradación";
  if (hi >= 70) return trend === "decreciente" ? "Moderada" : "Leve";
  if (hi >= 60) return "Severa";
  return "Crítica";
}
