import type { ReportDataset } from "../types";

export const granTierraReport: ReportDataset = {
  title: "Reporte Gran Tierra Energy",
  subtitle:
    "Construido con base en el documento Analisis Profundo Copower PUTN Junio 2026 (Costayaco y Vonu).",
  source: "Carpeta data/GTE (PDF + DOCX + XLSX de junio 2026)",
  kpiData: [
    { month: "Ene", availability: 0.94, reliability: 0.94, maintainability: 0.79, generationMwh: 3860, operationalLossesMwh: 340, contractualCompliance: 0.96 },
    { month: "Feb", availability: 0.93, reliability: 0.93, maintainability: 0.78, generationMwh: 3905, operationalLossesMwh: 335, contractualCompliance: 0.96 },
    { month: "Mar", availability: 0.92, reliability: 0.92, maintainability: 0.76, generationMwh: 3810, operationalLossesMwh: 360, contractualCompliance: 0.95 },
    { month: "Abr", availability: 0.93, reliability: 0.93, maintainability: 0.77, generationMwh: 3960, operationalLossesMwh: 330, contractualCompliance: 0.96 },
    { month: "May", availability: 0.9288, reliability: 0.9405, maintainability: 0.74, generationMwh: 3995, operationalLossesMwh: 345, contractualCompliance: 0.97 },
    { month: "Jun", availability: 0.9792, reliability: 0.9792, maintainability: 0.86, generationMwh: 4110.144, operationalLossesMwh: 290, contractualCompliance: 1.0 },
  ],
  kpiTargets: {
    availability: 0.97,
    reliability: 0.97,
    maintainability: 0.8,
    generationMwh: 4000,
    operationalLossesMwh: 320,
    contractualCompliance: 0.97,
  },
  badActors: [
    {
      equipment: "CPW06",
      system: "Sistema N Costayaco",
      criticality: "Media",
      frequency: 3,
      knownCause: "Intercooler con residuo, perturbacion de red y sobrecarga (eventos 03, 27 y 28-jun).",
      generationImpactMwh: 165,
      unavailabilityHours: 6,
    },
    {
      equipment: "MRU (causa externa)",
      system: "Proceso de campo",
      criticality: "Alta",
      frequency: 43,
      knownCause: "Paradas y maniobras de planta de recuperacion de liquidos.",
      generationImpactMwh: 420,
      unavailabilityHours: 95,
    },
    {
      equipment: "SIN / Red externa",
      system: "Interconexion electrica",
      criticality: "Alta",
      frequency: 52,
      knownCause: "Disparos, reconectadores y perturbaciones de red (eventos de causa comun).",
      generationImpactMwh: 260,
      unavailabilityHours: 37,
    },
    {
      equipment: "CPW04 / CPW05",
      system: "Auxiliares 480V",
      criticality: "Baja",
      frequency: 2,
      knownCause: "Apertura de totalizador principal, pendiente validar criterio de imputacion como falla.",
      generationImpactMwh: 35,
      unavailabilityHours: 2,
    },
  ],
  rca: [
    { status: "Pendiente", value: 2, color: "#fb7185" },
    { status: "En curso", value: 5, color: "#f59e0b" },
    { status: "Cerrado", value: 7, color: "#22c55e" },
  ],
  maintenancePlan: [
    {
      id: "GTE-M01",
      system: "CPW06",
      type: "Correctivo",
      proposal: "Ejecutar analisis de causa raiz especifico para las 3 salidas de junio.",
      basis: "Unidad dominante de recurrencia (MTBF 222.33 h).",
      manufacturerRecommendation: "Corregir modos de falla intercooler, red y sobrecarga antes de cierre de julio.",
    },
    {
      id: "GTE-M02",
      system: "CPW04",
      type: "Predictivo",
      proposal: "Mantener seguimiento reforzado por dos cierres adicionales.",
      basis: "Cambio de 4 eventos en mayo a 0 eventos en junio, con evento de proteccion no imputado.",
      manufacturerRecommendation: "Incluir evento del 23-jun en tendencia de protecciones 480V.",
    },
    {
      id: "GTE-M03",
      system: "JIN-11 / JIN-12",
      type: "Preventivo",
      proposal: "Seguimiento diferenciado en etapa de estabilizacion hasta su ingreso formal al sistema N.",
      basis: "Ventana de evaluacion de 19 dias y eventos por baja presion de gas CYC.",
      manufacturerRecommendation: "Definir criterio formal de incorporacion sistémica.",
    },
  ],
  actionPlan: [
    {
      id: "GTE-A01",
      action: "Cerrar RCA de CPW06 incluyendo los eventos del 03, 27 y 28-jun",
      owner: "Ing. Control GTE",
      dueDate: "2026-07-31",
      status: "En curso",
      evidence: "Bitacora PUTN junio + Data Soporte (429 registros)",
      expectedResult: "Reducir recurrencia y aumentar MTBF de CPW06",
    },
    {
      id: "GTE-A02",
      action: "Crear indicador conjunto de disponibilidad aguas arriba (MRU + SIN + presion CYC)",
      owner: "Operacion Campo + CoPower",
      dueDate: "2026-08-15",
      status: "Pendiente",
      evidence: "Consolidado PF cliente por causa raiz",
      expectedResult: "Gestionar causas externas con mayor impacto que las fallas propias",
    },
    {
      id: "GTE-A03",
      action: "Cuantificar sobrecosto por uso de respaldo diesel en eventos de causa comun",
      owner: "Planeacion Energetica",
      dueDate: "2026-08-10",
      status: "En curso",
      evidence: "Generacion diesel junio: 119,716 kWh",
      expectedResult: "Incorporar costo operativo en el analisis de confiabilidad",
    },
  ],
  summary: {
    copowerFailures: 7,
    totalEvents: 38,
    mtbfHours: 711.57,
    mttrHours: 2.86,
    actionsOverdue: null,
    rcaPending: null,
    hoursOperated: 4716,
    hoursStandby: 773,
    hoursPreventive: 24,
    hoursCorrective: 70,
    hoursFailureCopower: 70,
    hoursFailureClient: 156,
    energyGasKwh: 3499840,
    energyDieselKwh: 119716,
  },
  reliabilityTrend: [
    { month: "Ene", availability: 0.94, reliability: 0.94, mtbfHours: 640.25, mttrHours: 4.4 },
    { month: "Feb", availability: 0.93, reliability: 0.93, mtbfHours: 622.1, mttrHours: 4.2 },
    { month: "Mar", availability: 0.92, reliability: 0.92, mtbfHours: 571.8, mttrHours: 5.0 },
    { month: "Abr", availability: 0.93, reliability: 0.93, mtbfHours: 611.35, mttrHours: 4.7 },
    { month: "May", availability: 0.9288, reliability: 0.9405, mtbfHours: 500.39, mttrHours: 5.32 },
    { month: "Jun", availability: 0.9792, reliability: 0.9792, mtbfHours: 711.57, mttrHours: 2.86 },
  ],
  causePareto: [
    { cause: "Falla SIN / red externa", count: 52 },
    { cause: "Parada / maniobra MRU", count: 43 },
    { cause: "Baja presion de gas CYC", count: 40 },
    { cause: "Falla propia del equipo", count: 38 },
    { cause: "Maniobras operativas", count: 31 },
    { cause: "Mantenimiento programado", count: 6 },
  ],
  generationByAsset: [
    { asset: "Costayaco - gas", gasKwh: 3499840, dieselKwh: 0 },
    { asset: "Costayaco - diesel", gasKwh: 0, dieselKwh: 119716 },
    { asset: "Vonu", gasKwh: 490588, dieselKwh: 0 },
  ],
  generationByEquipment: [
    { equipo: "CPW01", campo: "COSTAYACO", energiaKwh: 356623.378, horasOperacion: 572, horasStandBy: 60, horasPP: 0, horasPFContr: 2, horasPFCli: 86, horasCalDia: 720, fallaEvento: 2 },
    { equipo: "CPW02", campo: "COSTAYACO", energiaKwh: 394125.269, horasOperacion: 652, horasStandBy: 43, horasPP: 0, horasPFContr: 0, horasPFCli: 25, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "CPW03", campo: "COSTAYACO", energiaKwh: 379616.662, horasOperacion: 607, horasStandBy: 83, horasPP: 4, horasPFContr: 5, horasPFCli: 21, horasCalDia: 672, fallaEvento: 1 },
    { equipo: "CPW04", campo: "COSTAYACO", energiaKwh: 565298.149, horasOperacion: 708, horasStandBy: 7, horasPP: 0, horasPFContr: 0, horasPFCli: 5, horasCalDia: 672, fallaEvento: 1 },
    { equipo: "CPW05", campo: "COSTAYACO", energiaKwh: 567694.181, horasOperacion: 699, horasStandBy: 8, horasPP: 7, horasPFContr: 1, horasPFCli: 5, horasCalDia: 672, fallaEvento: 2 },
    { equipo: "CPW06", campo: "COSTAYACO", energiaKwh: 540992.607, horasOperacion: 667, horasStandBy: 45, horasPP: 0, horasPFContr: 7, horasPFCli: 1, horasCalDia: 720, fallaEvento: 3 },
    { equipo: "CPW07", campo: "COSTAYACO", energiaKwh: 386221, horasOperacion: 605, horasStandBy: 90, horasPP: 0, horasPFContr: 5, horasPFCli: 20, horasCalDia: 672, fallaEvento: 1 },
    { equipo: "G101V", campo: "COSTAYACO", energiaKwh: 15967, horasOperacion: 24, horasStandBy: 696, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "G102J", campo: "COSTAYACO", energiaKwh: 49726, horasOperacion: 63, horasStandBy: 657, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "G102K", campo: "COSTAYACO", energiaKwh: 54023, horasOperacion: 76, horasStandBy: 644, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "JIN-01", campo: "VONU", energiaKwh: 257713, horasOperacion: 701, horasStandBy: 12, horasPP: 6, horasPFContr: 0, horasPFCli: 1, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "JIN-02", campo: "VONU", energiaKwh: 232875, horasOperacion: 697, horasStandBy: 6, horasPP: 7, horasPFContr: 0, horasPFCli: 10, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "JIN-10", campo: "COSTAYACO", energiaKwh: 172764, horasOperacion: 471, horasStandBy: 230, horasPP: 4, horasPFContr: 0, horasPFCli: 15, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "JIN-11", campo: "COSTAYACO", energiaKwh: 54249, horasOperacion: 140, horasStandBy: 316, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 384, fallaEvento: 0 },
    { equipo: "JIN-12", campo: "COSTAYACO", energiaKwh: 82256, horasOperacion: 225, horasStandBy: 231, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 384, fallaEvento: 0 },
  ],
  totalGenerationKwh: 4110144.246,
  eventLog: [
    {
      date: "2026-06-03",
      equipment: "CPW06",
      eventType: "Falla",
      cause: "Intercooler con exceso de residuo",
      downtimeHours: 2,
      responsible: "COPOWER",
      notes: "Cambio de intercooler; evento imputable a equipo.",
    },
    {
      date: "2026-06-05",
      equipment: "CPW01",
      eventType: "Falla",
      cause: "Falla flexible multiple de escape",
      downtimeHours: 2,
      responsible: "COPOWER",
      notes: "Correctivo posterior a evento del 02-jun.",
    },
    {
      date: "2026-06-11",
      equipment: "CPW03",
      eventType: "Falla",
      cause: "Detonacion de equipo",
      downtimeHours: 5,
      responsible: "COPOWER",
      notes: "Existe inconsistencia de fecha en bitacora (15/06).",
    },
    {
      date: "2026-06-23",
      equipment: "CPW04 / CPW05",
      eventType: "Falla",
      cause: "Apertura totalizador auxiliares 480V",
      downtimeHours: 2,
      responsible: "Externo",
      notes: "Pendiente validacion de criterio de imputacion.",
    },
    {
      date: "2026-06-27",
      equipment: "CPW06 / CPW07",
      eventType: "Falla",
      cause: "Perturbacion de red y sobretension",
      downtimeHours: 7,
      responsible: "Externo",
      notes: "Evento simultaneo por FDL de G56/G57.",
    },
    {
      date: "2026-06-28",
      equipment: "CPW05",
      eventType: "Falla",
      cause: "Potencia inversa y falla de gobernacion",
      downtimeHours: 1,
      responsible: "COPOWER",
      notes: "Salida manual para proteccion.",
    },
    {
      date: "2026-06-12",
      equipment: "Sistema Costayaco + Vonu",
      eventType: "Causa comun",
      cause: "Falla del SIN (SD general)",
      downtimeHours: 4,
      responsible: "Externo",
      notes: "Afecta multiple unidades del parque.",
    },
    {
      date: "2026-06-25",
      equipment: "CPW01, CPW02, CPW03, CPW07, JIN-10/11/12",
      eventType: "Causa comun",
      cause: "Parada de MRU por nivel alto NGL",
      downtimeHours: 8,
      responsible: "Cliente",
      notes: "Se activa respaldo diesel.",
    },
    {
      date: "2026-06-26",
      equipment: "CPW01-07 y JIN-10/12",
      eventType: "Causa comun",
      cause: "Disparo de C9 y reconectador RX",
      downtimeHours: 6,
      responsible: "Externo",
      notes: "Evento de red 34.5/13.2 kV.",
    },
    {
      date: "2026-06-30",
      equipment: "JIN-11 / JIN-12",
      eventType: "Operativo",
      cause: "Baja presion de gas CYC",
      downtimeHours: 3,
      responsible: "Cliente",
      notes: "Unidad en etapa de estabilizacion.",
    },
  ],
  machineIndicators: [
    { unidad: "CPW01", campo: "COSTAYACO", horasStandBy: 146, disponibilidadPct: 99.72, confiabilidadPct: 99.72, fallas: 1, mtbfLabel: "572.00", mttrHours: 2, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Tuvo 2 salidas en el Excel; 1 fue imputada al cliente (6/07) y no cuenta" },
    { unidad: "CPW02", campo: "COSTAYACO", horasStandBy: 68, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Sin eventos en el mes" },
    { unidad: "CPW03", campo: "COSTAYACO", horasStandBy: 104, disponibilidadPct: 98.75, confiabilidadPct: 99.31, fallas: 1, mtbfLabel: "607.00", mttrHours: 5, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Evento único, mayor MTTR del grupo de un evento" },
    { unidad: "CPW04", campo: "COSTAYACO", horasStandBy: 12, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Tuvo 1 salida en el Excel (6/23) pero fue imputada al cliente, no cuenta" },
    { unidad: "CPW05", campo: "COSTAYACO", horasStandBy: 13, disponibilidadPct: 98.89, confiabilidadPct: 99.86, fallas: 1, mtbfLabel: "699.00", mttrHours: 1, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Tuvo 2 salidas en el Excel; 1 fue imputada al cliente (6/23) y no cuenta" },
    { unidad: "CPW06", campo: "COSTAYACO", horasStandBy: 46, disponibilidadPct: 99.03, confiabilidadPct: 99.03, fallas: 3, mtbfLabel: "222.33", mttrHours: 2, riesgoTecnico: "RIESGO MEDIO", cumplimiento: "CUMPLE", detalle: "Activo dominante del mes: 3 fallas imputables (6/03, 6/27, 6/28), todas contractuales" },
    { unidad: "CPW07", campo: "COSTAYACO", horasStandBy: 110, disponibilidadPct: 99.31, confiabilidadPct: 99.31, fallas: 1, mtbfLabel: "605.00", mttrHours: 5, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Evento del 6/27, mismo incidente de red que afectó a CPW06" },
    { unidad: "JIN-10", campo: "COSTAYACO", horasStandBy: 245, disponibilidadPct: 99.44, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Sin eventos correctivos" },
    { unidad: "G101V", campo: "COSTAYACO", horasStandBy: 696, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Unidad diésel, sin eventos" },
    { unidad: "G102J", campo: "COSTAYACO", horasStandBy: 657, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Unidad diésel, sin eventos" },
    { unidad: "G102K", campo: "COSTAYACO", horasStandBy: 644, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Unidad diésel, sin eventos" },
    { unidad: "JIN-01", campo: "VONU", horasStandBy: 13, disponibilidadPct: 99.17, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Sin fallas; Vonu recupera 100%" },
    { unidad: "JIN-02", campo: "VONU", horasStandBy: 16, disponibilidadPct: 99.03, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Sin fallas; Vonu recupera 100%" },
    { unidad: "JIN-11", campo: "COSTAYACO (excluida del sistémico)", horasStandBy: null, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "N/A", detalle: "Evaluada individual, en estabilización (ventana ~19 días); no se suma al Sistema N" },
    { unidad: "JIN-12", campo: "COSTAYACO (excluida del sistémico)", horasStandBy: null, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "N/A", detalle: "Evaluada individual, en estabilización (ventana ~19 días); no se suma al Sistema N" },
    { unidad: "SISTEMA N", campo: "COSTAYACO", horasStandBy: 744, disponibilidadPct: 97.92, confiabilidadPct: 97.92, fallas: 7, mtbfLabel: "711.57", mttrHours: 2.86, riesgoTecnico: "RIESGO MEDIO", cumplimiento: "CUMPLE", detalle: "Mejora vs. mayo (+5.04pp Disp., +3.87pp Conf.), mismos 7 eventos que mayo pero menor severidad" },
    { unidad: "SISTEMA N", campo: "VONU", horasStandBy: 29, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Recuperación plena vs. mayo (95.97%/97.04%)" },
  ],
};
