import type { ReportDataset } from "../types";

export const granTierraReport: ReportDataset = {
  title: "Reporte Gran Tierra Energy",
  subtitle:
    "Indicadores oficiales donde hay fuente (julio y junio PDF; mayo sistémico citado en informe de junio). Ene–Abr: horas/fallas/energía del Excel Data Soporte.",
  source: "data/GTE (Ene–Jun) + data/Julio/GTE (XLSX Data Soporte + PDF Análisis Indicadores JUL 2026)",
  // kpiData es fallback; la app GTE usa GRAN_TIERRA_KPI_FROM_MONTHS.
  kpiData: [
    { month: "Ene", availability: null, reliability: null, maintainability: null, generationMwh: 0, operationalLossesMwh: null, contractualCompliance: null },
    { month: "Feb", availability: null, reliability: null, maintainability: null, generationMwh: 0, operationalLossesMwh: null, contractualCompliance: null },
    { month: "Mar", availability: null, reliability: null, maintainability: null, generationMwh: 0, operationalLossesMwh: null, contractualCompliance: null },
    { month: "Abr", availability: null, reliability: null, maintainability: null, generationMwh: 3649.33, operationalLossesMwh: null, contractualCompliance: null },
    { month: "May", availability: 0.9288, reliability: 0.9405, maintainability: null, generationMwh: 3955.182, operationalLossesMwh: null, contractualCompliance: null },
    { month: "Jun", availability: 0.9792, reliability: 0.9792, maintainability: null, generationMwh: 4110.144, operationalLossesMwh: null, contractualCompliance: null },
    { month: "Jul", availability: 0.8065, reliability: 1, maintainability: null, generationMwh: 4131.917, operationalLossesMwh: null, contractualCompliance: 0.8065 },
  ],
  kpiTargets: {
    availability: 0.98,
    reliability: 0.98,
    maintainability: 0.8,
    generationMwh: 4000,
    operationalLossesMwh: 320,
    contractualCompliance: 0.98,
  },
  analysisHighlights: [
    "Julio oficial (PDF): Costayaco Disp. 80.65% / Conf. 100% — no cumple meta ≥98%. Vonú Disp. 98.79% / Conf. 100% (cumple ≥90%). 5 FO-GE-033 (4 cascadas MRU + detonación CPW-04).",
    "La caída de disponibilidad en Costayaco (−17.27 pp vs jun) se atribuye a cambio de controles AGC4 (CPW01/03 registrados en sábana julio como M10 el 13–14; CPW02 en descarbonización 10–11), no a fallas.",
    "Energía julio Data Soporte: 4.131.917 kWh (gas CYC 3.515.954 = PDF Sistema CPW; diésel 133.081; Vonú 482.882). El PDF mezcla kWh diésel/Vonú en el anexo.",
    "Junio (referencia): Costayaco 97.92%/97.92%, 7 fallas COPOWER, MTBF 986.71 h / MTTR 2.60 h.",
    "CPW01/02/03 cierran julio en RIESGO ALTO / NO CUMPLE por disponibilidad (91.9–94.5%) pese a confiabilidad plena.",
  ],
  badActors: [
    {
      equipment: "MRU (causa externa)",
      system: "Proceso de campo",
      criticality: "Alta",
      frequency: 43,
      knownCause: "Paradas/maniobras de planta de recuperacion de liquidos; mayor generador de PF-cliente (95 h). DOCX junio.",
      generationImpactMwh: 0,
      unavailabilityHours: 95,
    },
    {
      equipment: "SIN / Red externa",
      system: "Interconexion electrica",
      criticality: "Alta",
      frequency: 52,
      knownCause: "Disparos, reconectadores y SD generales (12 y 15-jun); 37 h PF-cliente. DOCX junio.",
      generationImpactMwh: 0,
      unavailabilityHours: 37,
    },
    {
      equipment: "CPW06",
      system: "Sistema N Costayaco",
      criticality: "Media",
      frequency: 3,
      knownCause: "Activo dominante: intercooler/secuestrante (03) y perturbacion G56/G57 (27). 6 h PF_contr. Anexo junio.",
      generationImpactMwh: 0,
      unavailabilityHours: 7,
    },
    {
      equipment: "Baja presion gas CYC",
      system: "Suministro de pozos",
      criticality: "Media",
      frequency: 40,
      knownCause: "Clima/suministro de pozos; afecta sobre todo JIN-10/11/12 (14 h PF-cliente). DOCX junio.",
      generationImpactMwh: 0,
      unavailabilityHours: 14,
    },
    {
      equipment: "CPW03",
      system: "Sistema N Costayaco",
      criticality: "Baja",
      frequency: 1,
      knownCause: "11-jun: perturbación transitoria durante la operación; FS≈3,92 h; causa raíz no determinada. Anexo junio.",
      generationImpactMwh: 0,
      unavailabilityHours: 5,
    },
    {
      equipment: "CPW04 / CPW05",
      system: "Auxiliares 480V",
      criticality: "Baja",
      frequency: 2,
      knownCause: "FO-44 23–24/jun: 4 disparos EEP; RL sin selectividad + Isd/Ii 480 V en 1,5×. Ajuste final 8×/15×; efectividad pendiente.",
      generationImpactMwh: 0,
      unavailabilityHours: 3,
    },
  ],
  rca: [
    { status: "Pendiente", value: 0, color: "#fb7185" },
    { status: "En curso", value: 0, color: "#f59e0b" },
    { status: "Cerrado", value: 0, color: "#22c55e" },
  ],
  /** El DOCX/PDF de junio no publica un inventario formal de casos RCA con estados.
   * Solo recomienda abrir análisis de causa raíz para CPW06 (2 eventos). */
  rcaCases: [],
  commonCauseEvents: [
    {
      date: "2026-06-03",
      description: "Perdida de referencia de voltaje del bus; maniobras 13.2 kV barra B→A.",
      systemsAffected: "CPW03, CPW04, CPW05",
    },
    {
      date: "2026-06-12",
      description: "SD general por falla del SIN.",
      systemsAffected: "13 unidades Costayaco y Vonu",
    },
    {
      date: "2026-06-15",
      description: "Segunda SD general de campo por falla del SIN.",
      systemsAffected: "15 unidades (incl. JIN-11/JIN-12)",
    },
    {
      date: "2026-06-24",
      description: "Disparo reconectador 34.5 kV Jauno–Piamonte + fuga aceite Quincy.",
      systemsAffected: "CPW01-07, JIN-02, JIN-10/11/12, diesel",
    },
    {
      date: "2026-06-25",
      description: "Parada MRU por nivel alto NGL; respaldo con diesel G102J/G102K.",
      systemsAffected: "CPW01, CPW02, CPW03, CPW07, JIN-10/11",
    },
    {
      date: "2026-06-26",
      description: "FDL por disparo C9 y reconectador RX por sobrecorriente.",
      systemsAffected: "CPW01-07 y JIN-10/12",
    },
  ],
  /** Sin plan formal de mantenimiento en fuentes GTE; propuestas del DOCX se listan solo como texto en análisis de junio. */
  maintenancePlan: [],
  /** Sin tracker formal de acciones con fechas/estados en PDF/DOCX/Excel. */
  actionPlan: [],
  summary: {
    copowerFailures: 7,
    totalEvents: 42,
    mtbfHours: 986.71,
    mttrHours: 2.6,
    actionsOverdue: null,
    rcaPending: null,
    hoursOperated: 6907,
    hoursStandby: 3128,
    hoursPreventive: 28,
    hoursCorrective: 20,
    hoursFailureCopower: 18.22,
    hoursFailureClient: 179.38,
    energyGasKwh: 3499840,
    energyDieselKwh: 119716,
  },
  reliabilityTrend: [
    { month: "Ene", availability: null, reliability: null, mtbfHours: null, mttrHours: null },
    { month: "Feb", availability: null, reliability: null, mtbfHours: null, mttrHours: null },
    { month: "Mar", availability: null, reliability: null, mtbfHours: null, mttrHours: null },
    { month: "Abr", availability: null, reliability: null, mtbfHours: null, mttrHours: null },
    { month: "May", availability: 0.9288, reliability: 0.9405, mtbfHours: 500.39, mttrHours: 5.32 },
    { month: "Jun", availability: 0.9792, reliability: 0.9792, mtbfHours: 986.71, mttrHours: 2.6 },
    { month: "Jul", availability: 0.8065, reliability: 1, mtbfHours: null, mttrHours: 0 },
  ],
  /** Pareto DOCX junio §4 — solo válido para mes Jun. */
  causePareto: [
    { cause: "Falla SIN / red externa", count: 52, hoursPfClient: 37, unitsAffected: "CPW01-07, diesel, JIN-01/02, JIN-10" },
    { cause: "Parada / maniobra MRU", count: 43, hoursPfClient: 95, unitsAffected: "CPW01-03, CPW07, JIN-10/11/12" },
    { cause: "Baja presion de gas CYC", count: 40, hoursPfClient: 14, unitsAffected: "JIN-10, JIN-11, JIN-12" },
    { cause: "Falla propia del equipo", count: 38, hoursPfClient: 70, unitsAffected: "CPW01, CPW03-07" },
    { cause: "Maniobras operativas", count: 31, hoursPfClient: 10, unitsAffected: "CPW01-07, G101V/102J/102K" },
    { cause: "Mantenimiento programado", count: 6, hoursPfClient: 0, unitsAffected: "CPW03, CPW05, JIN-01, JIN-02" },
  ],
  generationByAsset: [
    { asset: "Costayaco - gas", gasKwh: 3499840, dieselKwh: 0 },
    { asset: "Costayaco - diesel", gasKwh: 0, dieselKwh: 119716 },
    { asset: "Vonu", gasKwh: 490588, dieselKwh: 0 },
  ],
  generationByEquipment: [
    { equipo: "CPW01", campo: "COSTAYACO", energiaKwh: 356623.378, horasOperacion: 572, horasStandBy: 60, horasPP: 0, horasPFContr: 5, horasPFCli: 83, horasCalDia: 720, fallaEvento: 2 },
    { equipo: "CPW02", campo: "COSTAYACO", energiaKwh: 394125.269, horasOperacion: 652, horasStandBy: 43, horasPP: 0, horasPFContr: 0, horasPFCli: 25, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "CPW03", campo: "COSTAYACO", energiaKwh: 379616.662, horasOperacion: 607, horasStandBy: 83, horasPP: 4, horasPFContr: 3.92, horasPFCli: 21, horasCalDia: 672, fallaEvento: 1 },
    { equipo: "CPW04", campo: "COSTAYACO", energiaKwh: 565298.149, horasOperacion: 708, horasStandBy: 7, horasPP: 0, horasPFContr: 1, horasPFCli: 4, horasCalDia: 672, fallaEvento: 1 },
    { equipo: "CPW05", campo: "COSTAYACO", energiaKwh: 567694.181, horasOperacion: 699, horasStandBy: 8, horasPP: 7, horasPFContr: 2, horasPFCli: 3, horasCalDia: 672, fallaEvento: 1 },
    { equipo: "CPW06", campo: "COSTAYACO", energiaKwh: 540992.607, horasOperacion: 667, horasStandBy: 45, horasPP: 0, horasPFContr: 6.3, horasPFCli: 1, horasCalDia: 720, fallaEvento: 2 },
    { equipo: "CPW07", campo: "COSTAYACO", energiaKwh: 386221, horasOperacion: 605, horasStandBy: 90, horasPP: 0, horasPFContr: 0, horasPFCli: 20, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "G101V", campo: "COSTAYACO", energiaKwh: 15967, horasOperacion: 24, horasStandBy: 696, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "G102J", campo: "COSTAYACO", energiaKwh: 49726, horasOperacion: 63, horasStandBy: 657, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "G102K", campo: "COSTAYACO", energiaKwh: 54023, horasOperacion: 76, horasStandBy: 644, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "JIN-01", campo: "VONU", energiaKwh: 257713, horasOperacion: 701, horasStandBy: 12, horasPP: 6, horasPFContr: 0, horasPFCli: 1, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "JIN-02", campo: "VONU", energiaKwh: 232875, horasOperacion: 697, horasStandBy: 6, horasPP: 7, horasPFContr: 0, horasPFCli: 10, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "JIN-10", campo: "COSTAYACO", energiaKwh: 172764, horasOperacion: 471, horasStandBy: 230, horasPP: 4, horasPFContr: 0, horasPFCli: 15, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "JIN-11", campo: "COSTAYACO", energiaKwh: 54249, horasOperacion: 140, horasStandBy: 316, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 384, fallaEvento: 0 },
    { equipo: "JIN-12", campo: "COSTAYACO", energiaKwh: 82256, horasOperacion: 225, horasStandBy: 231, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 384, fallaEvento: 0 },
  ],
  totalGenerationKwh: 4110144.246,
  eventLog: [
    {
      date: "2026-06-03",
      equipment: "CPW06",
      eventType: "Falla",
      cause: "Intercooler con exceso de residuo",
      downtimeHours: 4,
      responsible: "COPOWER",
      notes: "Cambio de intercooler; PF_contr 4 h · EVT-2026-06-03-CPW06.",
    },
    {
      date: "2026-06-05",
      equipment: "CPW01",
      eventType: "Falla",
      cause: "Falla flexible multiple de escape",
      downtimeHours: 2,
      responsible: "COPOWER",
      notes: "Correctivo posterior a evento del 02-jun.",
    },
    {
      date: "2026-06-07",
      equipment: "CPW01",
      eventType: "Falla",
      cause: "Detonación por señal errónea del relé K4",
      downtimeHours: 3,
      responsible: "COPOWER",
      notes: "Cambio de base y relé K4 · PF_contr 3 h.",
    },
    {
      date: "2026-06-11",
      equipment: "CPW03",
      eventType: "Falla",
      cause: "Perturbación transitoria durante la operación; salida automática de la unidad; retorno 19:25 sin daños físicos ni reemplazos",
      downtimeHours: 3.92,
      responsible: "COPOWER",
      notes: "FO-GE-033 v.01 · FS≈3,92 h · energía no generada ≈2.620 kWh (estimado). Causa raíz no determinada.",
    },
    {
      date: "2026-06-23",
      equipment: "CPW04 / CPW05",
      eventType: "Falla",
      cause: "Cascada EEP Jauno–Piamonte → RL no selectivo → disparos 480 V",
      downtimeHours: 3,
      responsible: "COPOWER",
      notes: "CPW04 1 h + CPW05 2 h PF_contr; iniciador externo EEP + habilitante interno COPOWER.",
    },
    {
      date: "2026-06-27",
      equipment: "CPW06",
      eventType: "Falla",
      cause: "Protección Q> tras salida MRU; FS≈2,30 h solo por tendencia (FO sin horas); ≈2.420 kWh nom.; causa raíz en investigación",
      downtimeHours: 2.3,
      responsible: "COPOWER",
      notes: "EVT-2026-06-27-CPW06 · FO sin horas oficiales · tendencia 03:17–05:35 aprox. · RCA en investigación.",
    },
    {
      date: "2026-06-28",
      equipment: "CPW01 / CPW02 / CPW03 / CPW05 / CPW06 / CPW07",
      eventType: "Falla",
      cause: "Perturbación externa 34,5 kV (gallinazo / salida de la máquina); FS=0,38 h (07:10–07:33); ≈1.730 kWh; sin fallas propias",
      downtimeHours: 0.38,
      responsible: "Externo",
      notes: "FO-GE-033 · EVT-2026-06-28-RED34KV-A · FS=0,38 h contingencia · ≈1.730 kWh · normalización completa posterior sin hora en reporte.",
    },
    {
      date: "2026-06-12",
      equipment: "Sistema Costayaco + Vonu",
      eventType: "Causa comun",
      cause: "Falla del SIN (SD general)",
      downtimeHours: 4,
      responsible: "Externo",
      notes: "Afecta multiple unidades del parque.",
    },
    {
      date: "2026-06-25",
      equipment: "CPW01, CPW02, CPW03, CPW07, JIN-10/11/12",
      eventType: "Causa comun",
      cause: "Parada de MRU por nivel alto NGL",
      downtimeHours: 8,
      responsible: "GTE",
      notes: "Se activa respaldo diesel.",
    },
    {
      date: "2026-06-26",
      equipment: "CPW01-07 y JIN-10/12",
      eventType: "Causa comun",
      cause: "Disparo de C9 y reconectador RX",
      downtimeHours: 6,
      responsible: "Externo",
      notes: "Evento de red 34.5/13.2 kV.",
    },
    {
      date: "2026-06-30",
      equipment: "JIN-11 / JIN-12",
      eventType: "Operativo",
      cause: "Baja presion de gas CYC",
      downtimeHours: 3,
      responsible: "GTE",
      notes: "Unidad en etapa de estabilizacion.",
    },
  ],
  machineIndicators: [
    { unidad: "CPW01", campo: "COSTAYACO", horasStandBy: 146, disponibilidadPct: 99.72, confiabilidadPct: 99.72, fallas: 2, mtbfLabel: "286.00", mttrHours: 2.5, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "2 fallas COPOWER: fuga junta de escape (6/05) y detonación por relé K4 (6/07), 5 h PF_contr" },
    { unidad: "CPW02", campo: "COSTAYACO", horasStandBy: 68, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Sin eventos en el mes" },
    { unidad: "CPW03", campo: "COSTAYACO", horasStandBy: 104, disponibilidadPct: 98.75, confiabilidadPct: 99.31, fallas: 1, mtbfLabel: "607.00", mttrHours: 3.92, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Evento único (6/11): perturbación transitoria; FS≈3,92 h; ≈2.620 kWh; causa raíz no determinada" },
    { unidad: "CPW04", campo: "COSTAYACO", horasStandBy: 12, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 1, mtbfLabel: "708.00", mttrHours: 1, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Familia 23–24/jun: 4 disparos EEP + descoordinación RL/480 V; reajuste final pendiente de validación" },
    { unidad: "CPW05", campo: "COSTAYACO", horasStandBy: 13, disponibilidadPct: 98.89, confiabilidadPct: 99.86, fallas: 1, mtbfLabel: "699.00", mttrHours: 2, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "1 falla COPOWER (23–24/jun). El evento del 28-jun fue una perturbación externa de red" },
    { unidad: "CPW06", campo: "COSTAYACO", horasStandBy: 46, disponibilidadPct: 99.03, confiabilidadPct: 99.03, fallas: 2, mtbfLabel: "333.50", mttrHours: 3.15, riesgoTecnico: "RIESGO MEDIO", cumplimiento: "CUMPLE", detalle: "2 fallas: intercooler 6/03 (4 h) y Q> 6/27 (2,30 h). El 6/28 fue externo" },
    { unidad: "CPW07", campo: "COSTAYACO", horasStandBy: 110, disponibilidadPct: 99.31, confiabilidadPct: 99.31, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Salida 6/27 consolidada en EVT-2026-06-27-CPW06; no se cuenta como falla separada" },
    { unidad: "JIN-10", campo: "COSTAYACO", horasStandBy: 245, disponibilidadPct: 99.44, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Sin eventos correctivos" },
    { unidad: "G101V", campo: "COSTAYACO", horasStandBy: 696, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Unidad diésel, sin eventos" },
    { unidad: "G102J", campo: "COSTAYACO", horasStandBy: 657, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Unidad diésel, sin eventos" },
    { unidad: "G102K", campo: "COSTAYACO", horasStandBy: 644, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Unidad diésel, sin eventos" },
    { unidad: "JIN-01", campo: "VONU", horasStandBy: 13, disponibilidadPct: 99.17, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Sin fallas; Vonu recupera 100%" },
    { unidad: "JIN-02", campo: "VONU", horasStandBy: 16, disponibilidadPct: 99.03, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Sin fallas; Vonu recupera 100%" },
    { unidad: "JIN-11", campo: "COSTAYACO (excluida del sistémico)", horasStandBy: null, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "N/A", detalle: "Evaluada individual, en estabilización (ventana ~19 días); no se suma al Sistema N" },
    { unidad: "JIN-12", campo: "COSTAYACO (excluida del sistémico)", horasStandBy: null, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "N/A", detalle: "Evaluada individual, en estabilización (ventana ~19 días); no se suma al Sistema N" },
    { unidad: "SISTEMA N", campo: "COSTAYACO", horasStandBy: 744, disponibilidadPct: 97.92, confiabilidadPct: 97.92, fallas: 7, mtbfLabel: "986.71", mttrHours: 2.6, riesgoTecnico: "RIESGO MEDIO", cumplimiento: "NO CUMPLE", detalle: "7 fallas COPOWER (18,22 h PF_contr). 28-jun externo FS=0,38 h no imputable." },
    { unidad: "SISTEMA N", campo: "VONU", horasStandBy: 29, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Recuperación plena vs. mayo (95.97%/97.04%)" },
  ],
};
