import type { ReportDataset } from "../types";

export const granTierraReport: ReportDataset = {
  title: "Reporte Gran Tierra Energy",
  subtitle:
    "Indicadores oficiales solo donde hay fuente (junio PDF/DOCX; mayo sistémico citado en informe de junio). Ene–Abr: solo horas/fallas/energía del Excel Data Soporte.",
  source: "Carpeta data/GTE (XLSX Ene–Jun; PDF+DOCX solo Junio 2026)",
  // kpiData es fallback; la app GTE usa GRAN_TIERRA_KPI_FROM_MONTHS.
  kpiData: [
    { month: "Ene", availability: null, reliability: null, maintainability: null, generationMwh: 0, operationalLossesMwh: null, contractualCompliance: null },
    { month: "Feb", availability: null, reliability: null, maintainability: null, generationMwh: 0, operationalLossesMwh: null, contractualCompliance: null },
    { month: "Mar", availability: null, reliability: null, maintainability: null, generationMwh: 0, operationalLossesMwh: null, contractualCompliance: null },
    { month: "Abr", availability: null, reliability: null, maintainability: null, generationMwh: 3649.33, operationalLossesMwh: null, contractualCompliance: null },
    { month: "May", availability: 0.9288, reliability: 0.9405, maintainability: null, generationMwh: 3955.182, operationalLossesMwh: null, contractualCompliance: null },
    { month: "Jun", availability: 0.9792, reliability: 0.9792, maintainability: null, generationMwh: 4110.144, operationalLossesMwh: null, contractualCompliance: null },
  ],
  kpiTargets: {
    availability: 0.98,
    reliability: 0.98,
    maintainability: 0.8,
    generationMwh: 4000,
    operationalLossesMwh: 320,
    contractualCompliance: 0.98,
  },
  analysisHighlights: [
    "Fuente oficial de Disp/Conf/MTBF/MTTR: informe junio (PDF/DOCX). Costayaco 97.92%/97.92% — bajo umbral contractual Orden 1 (≥98%). Vonú 100%/100%.",
    "Misma cantidad de fallas asociadas a COPOWER que mayo (7), con mejor severidad: MTBF 711.57 h y MTTR 2.86 h (valores del anexo junio).",
    "La recurrencia se traslada de CPW04 (mayo) a CPW06 (junio, 3 eventos, RIESGO MEDIO, MTBF 222.33 h) según anexo.",
    "MRU, SIN y presión CYC concentran más horas PF-cliente que las fallas propias (DOCX §4).",
    "Bitácora Excel junio: 38 eventos con PF/falla, 10 Falla_evento, 7 asociadas a COPOWER; 209 h afectadas (20 contractuales + 189 cliente).",
  ],
  badActors: [
    {
      equipment: "MRU (causa externa)",
      system: "Proceso de campo",
      criticality: "Alta",
      frequency: 43,
      knownCause: "Paradas/maniobras de planta de recuperacion de liquidos; mayor generador de PF-cliente (95 h). DOCX junio.",
      generationImpactMwh: 0,
      unavailabilityHours: 95,
    },
    {
      equipment: "SIN / Red externa",
      system: "Interconexion electrica",
      criticality: "Alta",
      frequency: 52,
      knownCause: "Disparos, reconectadores y SD generales (12 y 15-jun); 37 h PF-cliente. DOCX junio.",
      generationImpactMwh: 0,
      unavailabilityHours: 37,
    },
    {
      equipment: "CPW06",
      system: "Sistema N Costayaco",
      criticality: "Media",
      frequency: 3,
      knownCause: "Activo dominante: intercooler/secuestrante (03), perturbacion G56/G57 (27) y sobrecarga (28). 7 h PF_contr. Anexo junio.",
      generationImpactMwh: 0,
      unavailabilityHours: 7,
    },
    {
      equipment: "Baja presion gas CYC",
      system: "Suministro de pozos",
      criticality: "Media",
      frequency: 40,
      knownCause: "Clima/suministro de pozos; afecta sobre todo JIN-10/11/12 (14 h PF-cliente). DOCX junio.",
      generationImpactMwh: 0,
      unavailabilityHours: 14,
    },
    {
      equipment: "CPW03",
      system: "Sistema N Costayaco",
      criticality: "Baja",
      frequency: 1,
      knownCause: "Detonacion (11-jun): mayor MTTR individual del mes (5 h) entre eventos unicos. Anexo junio.",
      generationImpactMwh: 0,
      unavailabilityHours: 5,
    },
    {
      equipment: "CPW04 / CPW05",
      system: "Auxiliares 480V",
      criticality: "Baja",
      frequency: 2,
      knownCause: "Apertura totalizador 480V (23-jun); imputadas a cliente. Bitacora junio.",
      generationImpactMwh: 0,
      unavailabilityHours: 3,
    },
  ],
  rca: [
    { status: "Pendiente", value: 0, color: "#fb7185" },
    { status: "En curso", value: 0, color: "#f59e0b" },
    { status: "Cerrado", value: 0, color: "#22c55e" },
  ],
  /** El DOCX/PDF de junio no publica un inventario formal de casos RCA con estados.
   * Solo recomienda abrir análisis de causa raíz para CPW06 (3 eventos). */
  rcaCases: [],
  commonCauseEvents: [
    {
      date: "2026-06-03",
      description: "Perdida de referencia de voltaje del bus; maniobras 13.2 kV barra B→A.",
      systemsAffected: "CPW03, CPW04, CPW05",
    },
    {
      date: "2026-06-12",
      description: "SD general por falla del SIN.",
      systemsAffected: "13 unidades Costayaco y Vonu",
    },
    {
      date: "2026-06-15",
      description: "Segunda SD general de campo por falla del SIN.",
      systemsAffected: "15 unidades (incl. JIN-11/JIN-12)",
    },
    {
      date: "2026-06-24",
      description: "Disparo reconectador 34.5 kV Jauno–Piamonte + fuga aceite Quincy.",
      systemsAffected: "CPW01-07, JIN-02, JIN-10/11/12, diesel",
    },
    {
      date: "2026-06-25",
      description: "Parada MRU por nivel alto NGL; respaldo con diesel G102J/G102K.",
      systemsAffected: "CPW01, CPW02, CPW03, CPW07, JIN-10/11",
    },
    {
      date: "2026-06-26",
      description: "FDL por disparo C9 y reconectador RX por sobrecorriente.",
      systemsAffected: "CPW01-07 y JIN-10/12",
    },
  ],
  /** Sin plan formal de mantenimiento en fuentes GTE; propuestas del DOCX se listan solo como texto en análisis de junio. */
  maintenancePlan: [],
  /** Sin tracker formal de acciones con fechas/estados en PDF/DOCX/Excel. */
  actionPlan: [],
  summary: {
    copowerFailures: 7,
    totalEvents: 38,
    mtbfHours: 711.57,
    mttrHours: 2.86,
    actionsOverdue: null,
    rcaPending: null,
    hoursOperated: 6907,
    hoursStandby: 3128,
    hoursPreventive: 28,
    hoursCorrective: 20,
    hoursFailureCopower: 20,
    hoursFailureClient: 189,
    energyGasKwh: 3499840,
    energyDieselKwh: 119716,
  },
  reliabilityTrend: [
    { month: "Ene", availability: null, reliability: null, mtbfHours: null, mttrHours: null },
    { month: "Feb", availability: null, reliability: null, mtbfHours: null, mttrHours: null },
    { month: "Mar", availability: null, reliability: null, mtbfHours: null, mttrHours: null },
    { month: "Abr", availability: null, reliability: null, mtbfHours: null, mttrHours: null },
    { month: "May", availability: 0.9288, reliability: 0.9405, mtbfHours: 500.39, mttrHours: 5.32 },
    { month: "Jun", availability: 0.9792, reliability: 0.9792, mtbfHours: 711.57, mttrHours: 2.86 },
  ],
  /** Pareto DOCX junio §4 — solo válido para mes Jun. */
  causePareto: [
    { cause: "Falla SIN / red externa", count: 52, hoursPfClient: 37, unitsAffected: "CPW01-07, diesel, JIN-01/02, JIN-10" },
    { cause: "Parada / maniobra MRU", count: 43, hoursPfClient: 95, unitsAffected: "CPW01-03, CPW07, JIN-10/11/12" },
    { cause: "Baja presion de gas CYC", count: 40, hoursPfClient: 14, unitsAffected: "JIN-10, JIN-11, JIN-12" },
    { cause: "Falla propia del equipo", count: 38, hoursPfClient: 70, unitsAffected: "CPW01, CPW03-07" },
    { cause: "Maniobras operativas", count: 31, hoursPfClient: 10, unitsAffected: "CPW01-07, G101V/102J/102K" },
    { cause: "Mantenimiento programado", count: 6, hoursPfClient: 0, unitsAffected: "CPW03, CPW05, JIN-01, JIN-02" },
  ],
  generationByAsset: [
    { asset: "Costayaco - gas", gasKwh: 3499840, dieselKwh: 0 },
    { asset: "Costayaco - diesel", gasKwh: 0, dieselKwh: 119716 },
    { asset: "Vonu", gasKwh: 490588, dieselKwh: 0 },
  ],
  generationByEquipment: [
    { equipo: "CPW01", campo: "COSTAYACO", energiaKwh: 356623.378, horasOperacion: 572, horasStandBy: 60, horasPP: 0, horasPFContr: 2, horasPFCli: 86, horasCalDia: 720, fallaEvento: 2 },
    { equipo: "CPW02", campo: "COSTAYACO", energiaKwh: 394125.269, horasOperacion: 652, horasStandBy: 43, horasPP: 0, horasPFContr: 0, horasPFCli: 25, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "CPW03", campo: "COSTAYACO", energiaKwh: 379616.662, horasOperacion: 607, horasStandBy: 83, horasPP: 4, horasPFContr: 5, horasPFCli: 21, horasCalDia: 672, fallaEvento: 1 },
    { equipo: "CPW04", campo: "COSTAYACO", energiaKwh: 565298.149, horasOperacion: 708, horasStandBy: 7, horasPP: 0, horasPFContr: 0, horasPFCli: 5, horasCalDia: 672, fallaEvento: 1 },
    { equipo: "CPW05", campo: "COSTAYACO", energiaKwh: 567694.181, horasOperacion: 699, horasStandBy: 8, horasPP: 7, horasPFContr: 1, horasPFCli: 5, horasCalDia: 672, fallaEvento: 2 },
    { equipo: "CPW06", campo: "COSTAYACO", energiaKwh: 540992.607, horasOperacion: 667, horasStandBy: 45, horasPP: 0, horasPFContr: 7, horasPFCli: 1, horasCalDia: 720, fallaEvento: 3 },
    { equipo: "CPW07", campo: "COSTAYACO", energiaKwh: 386221, horasOperacion: 605, horasStandBy: 90, horasPP: 0, horasPFContr: 5, horasPFCli: 20, horasCalDia: 672, fallaEvento: 1 },
    { equipo: "G101V", campo: "COSTAYACO", energiaKwh: 15967, horasOperacion: 24, horasStandBy: 696, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "G102J", campo: "COSTAYACO", energiaKwh: 49726, horasOperacion: 63, horasStandBy: 657, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "G102K", campo: "COSTAYACO", energiaKwh: 54023, horasOperacion: 76, horasStandBy: 644, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "JIN-01", campo: "VONU", energiaKwh: 257713, horasOperacion: 701, horasStandBy: 12, horasPP: 6, horasPFContr: 0, horasPFCli: 1, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "JIN-02", campo: "VONU", energiaKwh: 232875, horasOperacion: 697, horasStandBy: 6, horasPP: 7, horasPFContr: 0, horasPFCli: 10, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "JIN-10", campo: "COSTAYACO", energiaKwh: 172764, horasOperacion: 471, horasStandBy: 230, horasPP: 4, horasPFContr: 0, horasPFCli: 15, horasCalDia: 672, fallaEvento: 0 },
    { equipo: "JIN-11", campo: "COSTAYACO", energiaKwh: 54249, horasOperacion: 140, horasStandBy: 316, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 384, fallaEvento: 0 },
    { equipo: "JIN-12", campo: "COSTAYACO", energiaKwh: 82256, horasOperacion: 225, horasStandBy: 231, horasPP: 0, horasPFContr: 0, horasPFCli: 0, horasCalDia: 384, fallaEvento: 0 },
  ],
  totalGenerationKwh: 4110144.246,
  eventLog: [
    {
      date: "2026-06-03",
      equipment: "CPW06",
      eventType: "Falla",
      cause: "Intercooler con exceso de residuo",
      downtimeHours: 2,
      responsible: "COPOWER",
      notes: "Cambio de intercooler; evento asociado a equipo.",
    },
    {
      date: "2026-06-05",
      equipment: "CPW01",
      eventType: "Falla",
      cause: "Falla flexible multiple de escape",
      downtimeHours: 2,
      responsible: "COPOWER",
      notes: "Correctivo posterior a evento del 02-jun.",
    },
    {
      date: "2026-06-11",
      equipment: "CPW03",
      eventType: "Falla",
      cause: "Detonacion de equipo",
      downtimeHours: 5,
      responsible: "COPOWER",
      notes: "Existe inconsistencia de fecha en bitacora (15/06).",
    },
    {
      date: "2026-06-23",
      equipment: "CPW04 / CPW05",
      eventType: "Falla",
      cause: "Apertura totalizador auxiliares 480V",
      downtimeHours: 2,
      responsible: "Externo",
      notes: "Pendiente validacion de criterio de imputacion.",
    },
    {
      date: "2026-06-27",
      equipment: "CPW06 / CPW07",
      eventType: "Falla",
      cause: "Perturbacion de red y sobretension",
      downtimeHours: 7,
      responsible: "Externo",
      notes: "Evento simultaneo por FDL de G56/G57.",
    },
    {
      date: "2026-06-28",
      equipment: "CPW05",
      eventType: "Falla",
      cause: "Potencia inversa y falla de gobernacion",
      downtimeHours: 1,
      responsible: "COPOWER",
      notes: "Salida manual para proteccion.",
    },
    {
      date: "2026-06-12",
      equipment: "Sistema Costayaco + Vonu",
      eventType: "Causa comun",
      cause: "Falla del SIN (SD general)",
      downtimeHours: 4,
      responsible: "Externo",
      notes: "Afecta multiple unidades del parque.",
    },
    {
      date: "2026-06-25",
      equipment: "CPW01, CPW02, CPW03, CPW07, JIN-10/11/12",
      eventType: "Causa comun",
      cause: "Parada de MRU por nivel alto NGL",
      downtimeHours: 8,
      responsible: "GTE",
      notes: "Se activa respaldo diesel.",
    },
    {
      date: "2026-06-26",
      equipment: "CPW01-07 y JIN-10/12",
      eventType: "Causa comun",
      cause: "Disparo de C9 y reconectador RX",
      downtimeHours: 6,
      responsible: "Externo",
      notes: "Evento de red 34.5/13.2 kV.",
    },
    {
      date: "2026-06-30",
      equipment: "JIN-11 / JIN-12",
      eventType: "Operativo",
      cause: "Baja presion de gas CYC",
      downtimeHours: 3,
      responsible: "GTE",
      notes: "Unidad en etapa de estabilizacion.",
    },
  ],
  machineIndicators: [
    { unidad: "CPW01", campo: "COSTAYACO", horasStandBy: 146, disponibilidadPct: 99.72, confiabilidadPct: 99.72, fallas: 1, mtbfLabel: "572.00", mttrHours: 2, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Tuvo 2 salidas en el Excel; 1 fue imputada al cliente (6/07) y no cuenta" },
    { unidad: "CPW02", campo: "COSTAYACO", horasStandBy: 68, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Sin eventos en el mes" },
    { unidad: "CPW03", campo: "COSTAYACO", horasStandBy: 104, disponibilidadPct: 98.75, confiabilidadPct: 99.31, fallas: 1, mtbfLabel: "607.00", mttrHours: 5, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Evento único, mayor MTTR del grupo de un evento" },
    { unidad: "CPW04", campo: "COSTAYACO", horasStandBy: 12, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Tuvo 1 salida en el Excel (6/23) pero fue imputada al cliente, no cuenta" },
    { unidad: "CPW05", campo: "COSTAYACO", horasStandBy: 13, disponibilidadPct: 98.89, confiabilidadPct: 99.86, fallas: 1, mtbfLabel: "699.00", mttrHours: 1, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Tuvo 2 salidas en el Excel; 1 fue imputada al cliente (6/23) y no cuenta" },
    { unidad: "CPW06", campo: "COSTAYACO", horasStandBy: 46, disponibilidadPct: 99.03, confiabilidadPct: 99.03, fallas: 3, mtbfLabel: "222.33", mttrHours: 2, riesgoTecnico: "RIESGO MEDIO", cumplimiento: "CUMPLE", detalle: "Activo dominante del mes: 3 fallas asociadas a COPOWER (6/03, 6/27, 6/28), todas contractuales" },
    { unidad: "CPW07", campo: "COSTAYACO", horasStandBy: 110, disponibilidadPct: 99.31, confiabilidadPct: 99.31, fallas: 1, mtbfLabel: "605.00", mttrHours: 5, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Evento del 6/27, mismo incidente de red que afectó a CPW06" },
    { unidad: "JIN-10", campo: "COSTAYACO", horasStandBy: 245, disponibilidadPct: 99.44, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Sin eventos correctivos" },
    { unidad: "G101V", campo: "COSTAYACO", horasStandBy: 696, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Unidad diésel, sin eventos" },
    { unidad: "G102J", campo: "COSTAYACO", horasStandBy: 657, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Unidad diésel, sin eventos" },
    { unidad: "G102K", campo: "COSTAYACO", horasStandBy: 644, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Unidad diésel, sin eventos" },
    { unidad: "JIN-01", campo: "VONU", horasStandBy: 13, disponibilidadPct: 99.17, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Sin fallas; Vonu recupera 100%" },
    { unidad: "JIN-02", campo: "VONU", horasStandBy: 16, disponibilidadPct: 99.03, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Sin fallas; Vonu recupera 100%" },
    { unidad: "JIN-11", campo: "COSTAYACO (excluida del sistémico)", horasStandBy: null, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "N/A", detalle: "Evaluada individual, en estabilización (ventana ~19 días); no se suma al Sistema N" },
    { unidad: "JIN-12", campo: "COSTAYACO (excluida del sistémico)", horasStandBy: null, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "N/A", detalle: "Evaluada individual, en estabilización (ventana ~19 días); no se suma al Sistema N" },
    { unidad: "SISTEMA N", campo: "COSTAYACO", horasStandBy: 744, disponibilidadPct: 97.92, confiabilidadPct: 97.92, fallas: 7, mtbfLabel: "711.57", mttrHours: 2.86, riesgoTecnico: "RIESGO MEDIO", cumplimiento: "NO CUMPLE", detalle: "Mejora vs. mayo (+5.04pp Disp., +3.87pp Conf.), mismos 7 eventos que mayo pero menor severidad. Meta Orden 1 ≥98% → No cumple." },
    { unidad: "SISTEMA N", campo: "VONU", horasStandBy: 29, disponibilidadPct: 100, confiabilidadPct: 100, fallas: 0, mtbfLabel: "Sin Fallas", mttrHours: 0, riesgoTecnico: "RIESGO BAJO", cumplimiento: "CUMPLE", detalle: "Recuperación plena vs. mayo (95.97%/97.04%)" },
  ],
};
