import {
  computeMphi,
  evaluationFromMphi,
  healthBandFromMphi,
  type CriticalityLevel,
  type ExpectedBenefits,
  type MaintenanceOptimizationPlan,
  type MaintenanceRecommendation,
  type MaintenanceStrategy,
  type EquipmentType,
  type OptimizationStatus,
} from "./maintenanceOptimizationTypes";

/** Bump si cambia el portafolio canónico GTE junio. */
export const GTE_JUNE_MSO_SEED = "2026-07-26-mso-r3";

function rec(
  planId: string,
  n: number,
  recommendation: string,
  priority: MaintenanceRecommendation["priority"],
  expectedBenefit: string,
  estimatedSavingsPct: number,
  implementationCost: number,
  responsible: string,
  status: MaintenanceRecommendation["status"],
  autoGenerated: boolean,
  trigger?: string,
): MaintenanceRecommendation {
  return {
    id: `${planId}-R${n}`,
    planId,
    recommendation,
    priority,
    expectedBenefit,
    estimatedSavingsPct,
    implementationCost,
    responsible,
    status,
    createdAt: "2026-06-30",
    autoGenerated,
    trigger,
  };
}

function plan(input: {
  id: string;
  assetId: string;
  assetName: string;
  equipmentType: EquipmentType;
  manufacturer: string;
  criticality: CriticalityLevel;
  currentStrategy: MaintenanceStrategy;
  currentFrequency: string;
  recommendedStrategy: MaintenanceStrategy;
  recommendedFrequency: string;
  optimizationStatus: OptimizationStatus;
  justification: string;
  expectedBenefit: string;
  benefits: ExpectedBenefits;
  operatingHours: number;
  availabilityPct: number;
  mtbfHours: number | null;
  mttrHours: number | null;
  failures: number;
  maintenanceCostUsd: number;
  outageHours: number;
  impactIndex: number;
  linkedRcaIds: string[];
  linkedPlanIds: string[];
  linkedEventHints: string[];
  recommendations: MaintenanceRecommendation[];
}): MaintenanceOptimizationPlan {
  const mphi = computeMphi({
    criticality: input.criticality,
    availabilityPct: input.availabilityPct,
    failures: input.failures,
    mtbfHours: input.mtbfHours,
    mttrHours: input.mttrHours,
    impactIndex: input.impactIndex,
  });
  return {
    ...input,
    mphi,
    healthBand: healthBandFromMphi(mphi),
    evaluation: evaluationFromMphi(mphi),
    createdAt: "2026-06-30",
    updatedAt: "2026-07-26",
  };
}

/**
 * Planes MSO · junio 2026 Gran Tierra / Costayaco.
 * Fuente: indicadores GTE + bitácora 7 fallas COPOWER (18,22 h PF_contr) · MTTR 2,60 · MTBF 986,71.
 * Enlazado a RCA-001…008 e IP-GTE-001…009.
 */
export function buildGteJuneMaintenanceOptimization(): MaintenanceOptimizationPlan[] {
  const p1 = "MSO-001";
  const p2 = "MSO-002";
  const p3 = "MSO-003";
  const p4 = "MSO-004";
  const p5 = "MSO-005";
  const p6 = "MSO-006";
  const p7 = "MSO-007";
  const p8 = "MSO-008";

  const plans = [
    plan({
      id: p1,
      assetId: "CPW06",
      assetName: "CPW06",
      equipmentType: "Motor",
      manufacturer: "Jenbacher / INNIO",
      criticality: "Muy Alta",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 500 h",
      recommendedStrategy: "Basado en Condición",
      recommendedFrequency: "Cada 400 h + predictivo mensual",
      optimizationStatus: "Requiere optimización",
      expectedBenefit: "Reducir fallas recurrentes y estabilizar MTBF",
      benefits: { mtbfPct: 22, availabilityPct: 0.7, mttrPct: -10, costPct: -4, failuresPct: -35 },
      operatingHours: 667,
      availabilityPct: 99.03,
      mtbfHours: 333.5,
      mttrHours: 3.15,
      failures: 2,
      maintenanceCostUsd: 18500,
      outageHours: 6.3,
      impactIndex: 8.2,
      linkedRcaIds: ["RCA-003", "RCA-004"],
      linkedPlanIds: ["IP-GTE-003", "IP-GTE-004"],
      linkedEventHints: ["Intercooler 03-jun · 4 h", "Q> 27-jun · 2,30 h"],
      justification:
        "Indicadores GTE junio: disp. 99.03% · 2 fallas · MTBF 333,5 h · MTTR 3,15 h · PF_contr 6,3 h (intercooler + Q>). Criticidad muy alta: acortar PM 500→400 h, termografía e inspección de intercooler por condición (RCA-003 / IP-GTE-003) y cerrar investigación AVR/Q> (RCA-004 / IP-GTE-004).",
      recommendations: [
        rec(p1, 1, "Reducir frecuencia preventiva 500 h → 400 h", "Crítica", "MTBF +22%", 4, 2500, "Confiabilidad", "En curso", true, "2 fallas contractuales junio"),
        rec(p1, 2, "Agregar inspección termográfica mensual", "Alta", "Detección temprana de hotspots", 3, 1800, "Eléctrico", "Abierta", true, "Índice de impacto >6"),
        rec(p1, 3, "Definir limpieza/inspección de intercooler por condición", "Alta", "Estabilizar ΔP / temperaturas", 2, 1200, "Mecánico", "Implementada", true, "RCA-003"),
        rec(p1, 4, "Validar configuración Q> / AVR DVC-550 post-MRU", "Alta", "Cerrar causa raíz 27-jun", 1, 900, "Eléctrico", "Abierta", true, "RCA-004 abierto"),
      ],
    }),
    plan({
      id: p2,
      assetId: "CPW03",
      assetName: "CPW03",
      equipmentType: "Motor",
      manufacturer: "Jenbacher / INNIO",
      criticality: "Alta",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 500 h",
      recommendedStrategy: "Predictivo",
      recommendedFrequency: "Cada 500 h + captura automática de transitorios",
      optimizationStatus: "En aprobación",
      expectedBenefit: "Cerrar causa raíz de evento transitorio y reducir MTTR",
      benefits: { mtbfPct: 18, availabilityPct: 0.9, mttrPct: -15, costPct: -3, failuresPct: -40 },
      operatingHours: 607,
      availabilityPct: 98.75,
      mtbfHours: 607,
      mttrHours: 3.92,
      failures: 1,
      maintenanceCostUsd: 14200,
      outageHours: 3.92,
      impactIndex: 6.5,
      linkedRcaIds: ["RCA-008"],
      linkedPlanIds: ["IP-GTE-009"],
      linkedEventHints: ["Perturbación transitoria 11-jun · FS≈3,92 h · ≈2.620 kWh"],
      justification:
        "Indicadores GTE: disp. 98.75% · 1 falla · MTBF 607 h · MTTR 3,92 h. RCA-008: causa raíz no determinada. Mantener PM 500 h e incorporar captura automática de diagnóstico (IP-GTE-009); no atribuir a detonación/combustión.",
      recommendations: [
        rec(p2, 1, "Recuperar históricos de variables en la ventana del evento", "Crítica", "Cerrar diagnóstico", 3, 4200, "Confiabilidad", "En curso", true, "Causa raíz no determinada"),
        rec(p2, 2, "Fortalecer captura automática ante transitorios", "Alta", "Evidencia para RCA", 2, 1500, "Instrumentación", "Abierta", false),
        rec(p2, 3, "Confirmar energía no generada con totalizadores", "Media", "Cuadrar kWh FO", 1, 800, "Operaciones", "Abierta", false),
      ],
    }),
    plan({
      id: p3,
      assetId: "CPW01",
      assetName: "CPW01",
      equipmentType: "Motor",
      manufacturer: "Jenbacher / INNIO",
      criticality: "Alta",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 500 h",
      recommendedStrategy: "Preventivo",
      recommendedFrequency: "Cada 500 h + checklista escape + bases relé",
      optimizationStatus: "Implementado",
      expectedBenefit: "Evitar reincidencias escape (05-jun) y K4 (07-jun)",
      benefits: { mtbfPct: 12, availabilityPct: 0.3, mttrPct: -8, costPct: -2, failuresPct: -25 },
      operatingHours: 572,
      availabilityPct: 99.72,
      mtbfHours: 286,
      mttrHours: 2.5,
      failures: 2,
      maintenanceCostUsd: 9800,
      outageHours: 5,
      impactIndex: 5.1,
      linkedRcaIds: ["RCA-001", "RCA-002"],
      linkedPlanIds: ["IP-GTE-001", "IP-GTE-002"],
      linkedEventHints: ["Flexible escape 05-jun · 2 h", "Relé K4 07-jun · 3 h"],
      justification:
        "Indicadores GTE: disp. 99.72% · 2 fallas · MTBF 286 h · MTTR 2,5 h · PF_contr 5 h. RCA-002/001 e IP-GTE-002/001 cerrados: checklist de montaje escape y bases de relé en correctivos eléctricos.",
      recommendations: [
        rec(p3, 1, "Mantener checklist de torque post-mto de escape/admisión", "Alta", "Cero reincidencias escape", 2, 800, "Mecánico", "Implementada", true, "RCA-002"),
        rec(p3, 2, "Incluir bases de relé en checklist eléctrico post-evento", "Alta", "Cero reincidencias K4", 1, 200, "Eléctrico", "Implementada", true, "RCA-001"),
      ],
    }),
    plan({
      id: p4,
      assetId: "MRU",
      assetName: "MRU",
      equipmentType: "MRU",
      manufacturer: "Campo / Gran Tierra",
      criticality: "Muy Alta",
      currentStrategy: "Correctivo",
      currentFrequency: "Reactivo / semanal ad-hoc",
      recommendedStrategy: "Predictivo",
      recommendedFrequency: "Monitoreo continuo NGL + PM semanal",
      optimizationStatus: "Requiere optimización",
      expectedBenefit: "Subir disponibilidad del sistema de tratamiento",
      benefits: { mtbfPct: 30, availabilityPct: 1.5, mttrPct: -20, costPct: 5, failuresPct: -45 },
      operatingHours: 720,
      availabilityPct: 92.5,
      mtbfHours: 96,
      mttrHours: 8,
      failures: 4,
      maintenanceCostUsd: 26000,
      outageHours: 48,
      impactIndex: 9.1,
      linkedRcaIds: ["RCA-006"],
      linkedPlanIds: ["IP-GTE-006"],
      linkedEventHints: ["Mto MRU 02-jun", "NGL 25-jun", "Habilitante Q> 27-jun / externo 28-jun"],
      justification:
        "MRU (GTE): paradas por NGL/mto habilitan fallas en generadores y elevan PF_cli. Disp. estimada <98%. RCA-006 / IP-GTE-006: pasar de correctivo reactivo a predictivo con alarmas NGL y PM semanal formal.",
      recommendations: [
        rec(p4, 1, "Incrementar mantenimiento predictivo (NGL / alarmas tempranas)", "Crítica", "Disp. sistema +1.5%", 0, 12000, "Gran Tierra", "En curso", true, "Disponibilidad <98%"),
        rec(p4, 2, "Programa de mantenimiento preventivo semanal formal", "Crítica", "Fallas -45%", 0, 6000, "Gran Tierra", "Abierta", true, "Impacto sistémico alto"),
        rec(p4, 3, "Optimizar procedimiento operativo post-NGL", "Alta", "MTTR -20%", 2, 1500, "Operación GTE", "Abierta", false),
      ],
    }),
    plan({
      id: p5,
      assetId: "CPW05",
      assetName: "CPW05",
      equipmentType: "Motor",
      manufacturer: "Jenbacher / INNIO",
      criticality: "Alta",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 1000 h",
      recommendedStrategy: "RCM",
      recommendedFrequency: "Tras evento EEP + validación selectividad 480 V",
      optimizationStatus: "En aprobación",
      expectedBenefit: "Evitar reincidencia FO-44 en auxiliares / unidad",
      benefits: { mtbfPct: 15, availabilityPct: 0.5, mttrPct: -12, costPct: -1, failuresPct: -30 },
      operatingHours: 699,
      availabilityPct: 98.89,
      mtbfHours: 699,
      mttrHours: 2,
      failures: 1,
      maintenanceCostUsd: 7600,
      outageHours: 2,
      impactIndex: 6.8,
      linkedRcaIds: ["RCA-007"],
      linkedPlanIds: ["IP-GTE-007"],
      linkedEventHints: ["FO-44 23-jun · PF_contr 2 h"],
      justification:
        "Indicadores GTE: disp. 98.89% · 1 falla · MTBF 699 h · MTTR 2 h · PF_contr 2 h (FO-44). El 28-jun fue externo (no imputable). RCA-007 / IP-GTE-007: validar ajuste 8×/15× y selectividad RL/480 V.",
      recommendations: [
        rec(p5, 1, "Validar efectividad del ajuste 8×/15× (FO-44)", "Crítica", "Sin SD 480 V ante EEP", 1, 2000, "Eléctrico", "En curso", true, "RCA-007 abierto"),
        rec(p5, 2, "Inspeccionar respuesta de gobernación post-redistribución de carga", "Alta", "Sin anomalías", 1, 1800, "Instrumentación", "Implementada", false),
      ],
    }),
    plan({
      id: p6,
      assetId: "CPW07",
      assetName: "CPW07",
      equipmentType: "AVR",
      manufacturer: "Jenbacher / INNIO",
      criticality: "Alta",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 2000 h",
      recommendedStrategy: "Basado en Condición",
      recommendedFrequency: "Tras perturbación + trimestral",
      optimizationStatus: "En aprobación",
      expectedBenefit: "Coordinar AVR/protecciones con CPW06 en transitorios MRU",
      benefits: { mtbfPct: 10, availabilityPct: 0.4, mttrPct: -5, costPct: 0, failuresPct: -20 },
      operatingHours: 605,
      availabilityPct: 99.31,
      mtbfHours: null,
      mttrHours: 0,
      failures: 0,
      maintenanceCostUsd: 5400,
      outageHours: 0,
      impactIndex: 4.2,
      linkedRcaIds: ["RCA-004"],
      linkedPlanIds: ["IP-GTE-004"],
      linkedEventHints: ["Participación en investigación Q> 27-jun (falla consolidada en CPW06)"],
      justification:
        "Indicadores GTE: disp. 99.31% · 0 fallas (salida 27-jun consolidada en EVT CPW06). Seguimiento AVR/DEIF como activo vinculado a RCA-004 / IP-GTE-004; no imputar falla separada a CPW07.",
      recommendations: [
        rec(p6, 1, "Analizar comportamiento conjunto CPW-06 / CPW-07 en evento Q>", "Alta", "Coordinación eléctrica", 1, 700, "Confiabilidad", "Abierta", true, "RCA-004"),
        rec(p6, 2, "Validar configuración AVR / protecciones post-perturbación", "Alta", "Cerrar investigación", 0, 900, "Eléctrico", "Abierta", false),
      ],
    }),
    plan({
      id: p7,
      assetId: "CPW02",
      assetName: "CPW02",
      equipmentType: "Motor",
      manufacturer: "Jenbacher / INNIO",
      criticality: "Media",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 250 h",
      recommendedStrategy: "Preventivo",
      recommendedFrequency: "Cada 500 h",
      optimizationStatus: "Validado",
      expectedBenefit: "Reducir sobre-mantenimiento sin degradar confiabilidad",
      benefits: { mtbfPct: 0, availabilityPct: 0.1, mttrPct: 0, costPct: -12, failuresPct: 0 },
      operatingHours: 652,
      availabilityPct: 100,
      mtbfHours: null,
      mttrHours: 0,
      failures: 0,
      maintenanceCostUsd: 11200,
      outageHours: 0,
      impactIndex: 1.2,
      linkedRcaIds: [],
      linkedPlanIds: [],
      linkedEventHints: ["Sin fallas contractuales en junio"],
      justification:
        "Indicadores GTE: disp. 100% · 0 fallas. Frecuencia 250 h sugiere sobre-mantenimiento: extender a 500 h alineado al parque, liberando capacidad sin aumentar riesgo.",
      recommendations: [
        rec(p7, 1, "Extender frecuencia preventiva 250 h → 500 h", "Media", "Costo -12%", 12, 0, "Confiabilidad", "Implementada", true, "Sin fallas + alta disponibilidad"),
        rec(p7, 2, "Eliminar actividad redundante de inspección intermedia", "Baja", "Horas-hombre -8%", 8, 0, "Mecánico", "Implementada", false),
      ],
    }),
    plan({
      id: p8,
      assetId: "CPW04",
      assetName: "CPW04",
      equipmentType: "Generador",
      manufacturer: "Jenbacher / INNIO",
      criticality: "Alta",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 1000 h",
      recommendedStrategy: "Basado en Condición",
      recommendedFrequency: "Tras evento EEP + validación selectividad 480 V",
      optimizationStatus: "En aprobación",
      expectedBenefit: "Evitar cascada FO-44 a auxiliares 480 V",
      benefits: { mtbfPct: 10, availabilityPct: 0.4, mttrPct: -8, costPct: -2, failuresPct: -25 },
      operatingHours: 708,
      availabilityPct: 100,
      mtbfHours: 708,
      mttrHours: 1,
      failures: 1,
      maintenanceCostUsd: 6100,
      outageHours: 1,
      impactIndex: 5.5,
      linkedRcaIds: ["RCA-007"],
      linkedPlanIds: ["IP-GTE-007"],
      linkedEventHints: ["FO-44 23-jun · PF_contr 1 h"],
      justification:
        "Indicadores GTE: disp. 100% · 1 falla · MTBF 708 h · MTTR 1 h · PF_contr 1 h (FO-44 familia 23–24/jun). RCA-007 / IP-GTE-007: estudio de coordinación y validación del ajuste 8×/15× pendiente.",
      recommendations: [
        rec(p8, 1, "Completar estudio de coordinación 34,5 kV → RL → 480 V", "Crítica", "Selectividad demostrada", 2, 3500, "Eléctrico", "Abierta", true, "RCA-007"),
        rec(p8, 2, "Validar data TRIP post-ajuste 8×/15×", "Alta", "Sin reincidencia FO-44", 1, 800, "Eléctrico", "Abierta", false),
      ],
    }),
  ];

  return [...plans].sort((a, b) => a.mphi - b.mphi || b.impactIndex - a.impactIndex);
}

export function strategyMix(plans: MaintenanceOptimizationPlan[]) {
  const counts = new Map<MaintenanceStrategy, number>();
  for (const p of plans) {
    counts.set(p.recommendedStrategy, (counts.get(p.recommendedStrategy) ?? 0) + 1);
  }
  const total = plans.length || 1;
  return [...counts.entries()]
    .map(([name, count]) => ({ name, count, pct: Math.round((count / total) * 100) }))
    .sort((a, b) => b.count - a.count);
}

export function topOpportunities(plans: MaintenanceOptimizationPlan[], limit = 4) {
  return [...plans]
    .filter((p) => p.healthBand !== "Excelente" || p.optimizationStatus === "Requiere optimización")
    .sort((a, b) => a.mphi - b.mphi || b.impactIndex - a.impactIndex)
    .slice(0, limit)
    .map((p) => ({
      assetId: p.assetId,
      action: p.recommendations[0]?.recommendation ?? p.expectedBenefit,
      mphi: p.mphi,
      healthBand: p.healthBand,
      impactIndex: p.impactIndex,
    }));
}

export function portfolioKpis(plans: MaintenanceOptimizationPlan[]) {
  const optimized = plans.filter(
    (p) => p.optimizationStatus === "Implementado" || p.optimizationStatus === "Validado",
  ).length;
  const avgCostSaving =
    plans.reduce((acc, p) => acc + Math.abs(Math.min(0, p.benefits.costPct)), 0) /
    (plans.length || 1);
  const avgAvailGain =
    plans.reduce((acc, p) => acc + p.benefits.availabilityPct, 0) / (plans.length || 1);
  const avgFailDrop =
    plans.reduce((acc, p) => acc + Math.abs(p.benefits.failuresPct), 0) / (plans.length || 1);
  return {
    assetsAnalyzed: plans.length,
    plansEvaluated: plans.length,
    plansOptimized: optimized,
    estimatedSavingsPct: Number(avgCostSaving.toFixed(1)),
    expectedAvailabilityGain: Number(avgAvailGain.toFixed(2)),
    expectedFailureReduction: Math.round(avgFailDrop),
  };
}
