import {
  computeMphi,
  evaluationFromMphi,
  healthBandFromMphi,
  type CriticalityLevel,
  type ExpectedBenefits,
  type MaintenanceOptimizationPlan,
  type MaintenanceRecommendation,
  type MaintenanceStrategy,
  type EquipmentType,
  type OptimizationStatus,
} from "./maintenanceOptimizationTypes";

function rec(
  planId: string,
  n: number,
  recommendation: string,
  priority: MaintenanceRecommendation["priority"],
  expectedBenefit: string,
  estimatedSavingsPct: number,
  implementationCost: number,
  responsible: string,
  status: MaintenanceRecommendation["status"],
  autoGenerated: boolean,
  trigger?: string,
): MaintenanceRecommendation {
  return {
    id: `${planId}-R${n}`,
    planId,
    recommendation,
    priority,
    expectedBenefit,
    estimatedSavingsPct,
    implementationCost,
    responsible,
    status,
    createdAt: "2026-06-30",
    autoGenerated,
    trigger,
  };
}

function plan(input: {
  id: string;
  assetId: string;
  assetName: string;
  equipmentType: EquipmentType;
  manufacturer: string;
  criticality: CriticalityLevel;
  currentStrategy: MaintenanceStrategy;
  currentFrequency: string;
  recommendedStrategy: MaintenanceStrategy;
  recommendedFrequency: string;
  optimizationStatus: OptimizationStatus;
  justification: string;
  expectedBenefit: string;
  benefits: ExpectedBenefits;
  operatingHours: number;
  availabilityPct: number;
  mtbfHours: number | null;
  mttrHours: number | null;
  failures: number;
  maintenanceCostUsd: number;
  outageHours: number;
  impactIndex: number;
  linkedRcaIds: string[];
  linkedPlanIds: string[];
  linkedEventHints: string[];
  recommendations: MaintenanceRecommendation[];
}): MaintenanceOptimizationPlan {
  const mphi = computeMphi({
    criticality: input.criticality,
    availabilityPct: input.availabilityPct,
    failures: input.failures,
    mtbfHours: input.mtbfHours,
    mttrHours: input.mttrHours,
    impactIndex: input.impactIndex,
  });
  return {
    ...input,
    mphi,
    healthBand: healthBandFromMphi(mphi),
    evaluation: evaluationFromMphi(mphi),
    createdAt: "2026-06-30",
    updatedAt: "2026-07-21",
  };
}

/** Planes MSO · junio 2026 Gran Tierra / flota Costayaco — no es CMMS. */
export function buildGteJuneMaintenanceOptimization(): MaintenanceOptimizationPlan[] {
  const p1 = "MSO-001";
  const p2 = "MSO-002";
  const p3 = "MSO-003";
  const p4 = "MSO-004";
  const p5 = "MSO-005";
  const p6 = "MSO-006";
  const p7 = "MSO-007";
  const p8 = "MSO-008";

  return [
    plan({
      id: p1,
      assetId: "CPW06",
      assetName: "CPW06",
      equipmentType: "Motor",
      manufacturer: "Caterpillar",
      criticality: "Muy Alta",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 500 h",
      recommendedStrategy: "Basado en Condición",
      recommendedFrequency: "Cada 400 h + predictivo mensual",
      optimizationStatus: "Requiere optimización",
      expectedBenefit: "Reducir fallas recurrentes y estabilizar MTBF",
      benefits: { mtbfPct: 22, availabilityPct: 0.7, mttrPct: -10, costPct: -4, failuresPct: -35 },
      operatingHours: 667,
      availabilityPct: 99.03,
      mtbfHours: 222.33,
      mttrHours: 2,
      failures: 3,
      maintenanceCostUsd: 18500,
      outageHours: 8,
      impactIndex: 8.2,
      linkedRcaIds: ["RCA-003", "RCA-004", "RCA-005"],
      linkedPlanIds: ["IP-GTE-003", "IP-GTE-004", "IP-GTE-005"],
      linkedEventHints: ["Intercooler 03-jun", "Perturbación 27-jun", "Sobrecarga 28-jun"],
      justification:
        "CPW06 concentra 3 fallas contractuales en junio (MTBF 222 h). Con criticidad muy alta no aplica Run To Failure. Se recomienda acortar el preventivo de 500 a 400 h e incorporar termografía e inspección de intercooler por condición, alineado a RCA-003 y al IIO dominante del mes.",
      recommendations: [
        rec(p1, 1, "Reducir frecuencia preventiva 500 h → 400 h", "Crítica", "MTBF +22%", 4, 2500, "Confiabilidad", "En curso", true, "≥3 fallas en el trimestre"),
        rec(p1, 2, "Agregar inspección termográfica mensual", "Alta", "Detección temprana de hotspots", 3, 1800, "Eléctrico", "Abierta", true, "Índice de impacto >6"),
        rec(p1, 3, "Definir limpieza/inspección de intercooler por condición", "Alta", "Estabilizar temperaturas", 2, 1200, "Mecánico", "Implementada", false),
        rec(p1, 4, "Eliminar actividad redundante de inspección visual semanal sin criterio", "Media", "Costo -5%", 5, 0, "Confiabilidad", "Abierta", false),
      ],
    }),
    plan({
      id: p2,
      assetId: "CPW03",
      assetName: "CPW03",
      equipmentType: "Motor",
      manufacturer: "Caterpillar",
      criticality: "Alta",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 500 h",
      recommendedStrategy: "Predictivo",
      recommendedFrequency: "Cada 500 h + monitoreo combustión",
      optimizationStatus: "En aprobación",
      expectedBenefit: "Prevenir detonaciones y reducir MTTR",
      benefits: { mtbfPct: 18, availabilityPct: 0.9, mttrPct: -15, costPct: -3, failuresPct: -40 },
      operatingHours: 607,
      availabilityPct: 98.75,
      mtbfHours: 607,
      mttrHours: 5,
      failures: 1,
      maintenanceCostUsd: 14200,
      outageHours: 5,
      impactIndex: 6.5,
      linkedRcaIds: ["RCA-001"],
      linkedPlanIds: ["IP-GTE-001"],
      linkedEventHints: ["Detonación 11-jun"],
      justification:
        "Disponibilidad 98.75% (alerta <98% contractual sistema). El RCA-001 vincula detonación a calidad/presión de gas y parámetros de combustión. Mantener preventivo 500 h e incorporar monitoreo predictivo de combustión y presión de gas; no reducir a Run To Failure por criticidad alta.",
      recommendations: [
        rec(p2, 1, "Agregar monitoreo de temperatura y presión de gas", "Crítica", "Disponibilidad +0.9%", 3, 4200, "Instrumentación", "En curso", true, "Disponibilidad <98% (unidad)"),
        rec(p2, 2, "Calibrar parámetros de combustión tras cada intervención mayor", "Alta", "Cero detonaciones", 2, 1500, "Confiabilidad", "Implementada", false),
        rec(p2, 3, "Agregar análisis de vibraciones trimestral", "Media", "MTTR -12%", 1, 2200, "Predictivo", "Abierta", false),
      ],
    }),
    plan({
      id: p3,
      assetId: "CPW01",
      assetName: "CPW01",
      equipmentType: "Motor",
      manufacturer: "Caterpillar",
      criticality: "Alta",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 500 h",
      recommendedStrategy: "Preventivo",
      recommendedFrequency: "Cada 500 h + checklista admisión",
      optimizationStatus: "Implementado",
      expectedBenefit: "Evitar reincidencias en sistema de admisión",
      benefits: { mtbfPct: 12, availabilityPct: 0.3, mttrPct: -8, costPct: -2, failuresPct: -25 },
      operatingHours: 572,
      availabilityPct: 99.72,
      mtbfHours: 572,
      mttrHours: 2,
      failures: 1,
      maintenanceCostUsd: 9800,
      outageHours: 2,
      impactIndex: 5.1,
      linkedRcaIds: ["RCA-002"],
      linkedPlanIds: ["IP-GTE-002"],
      linkedEventHints: ["Daño admisión / flexible"],
      justification:
        "RCA-002 evidencia desgaste progresivo del conjunto de admisión. El plan preventivo base es adecuado; se actualiza el procedimiento de montaje y se agrega checklist pre-arranque. Misma familia de falla no debe repetirse sin modificar el procedimiento de mantenimiento.",
      recommendations: [
        rec(p3, 1, "Modificar procedimiento de mantenimiento de admisión", "Alta", "Cero reincidencias", 2, 800, "Mecánico", "Implementada", true, "RCA repetible / misma familia"),
        rec(p3, 2, "Lista de verificación antes del arranque", "Media", "MTTR -8%", 1, 200, "Operación", "Implementada", false),
      ],
    }),
    plan({
      id: p4,
      assetId: "MRU",
      assetName: "MRU",
      equipmentType: "MRU",
      manufacturer: "Campo / GTE",
      criticality: "Muy Alta",
      currentStrategy: "Correctivo",
      currentFrequency: "Reactivo / semanal ad-hoc",
      recommendedStrategy: "Predictivo",
      recommendedFrequency: "Monitoreo continuo NGL + PM semanal",
      optimizationStatus: "Requiere optimización",
      expectedBenefit: "Subir disponibilidad del sistema de tratamiento",
      benefits: { mtbfPct: 30, availabilityPct: 1.5, mttrPct: -20, costPct: 5, failuresPct: -45 },
      operatingHours: 720,
      availabilityPct: 92.5,
      mtbfHours: 96,
      mttrHours: 8,
      failures: 4,
      maintenanceCostUsd: 26000,
      outageHours: 48,
      impactIndex: 9.1,
      linkedRcaIds: ["RCA-006", "RCA-005"],
      linkedPlanIds: ["IP-GTE-006", "IP-GTE-005"],
      linkedEventHints: ["Parada NGL 25-jun", "Salida MRU 28-jun"],
      justification:
        "La MRU es el activo de mayor impacto sistémico: paradas por NGL afectan múltiples generadores. Disponibilidad <98% dispara alerta automática. Criticidad muy alta excluye Run To Failure. Se propone pasar de correctivo reactivo a predictivo con alarmas tempranas de NGL y PM estructurado.",
      recommendations: [
        rec(p4, 1, "Incrementar mantenimiento predictivo (NGL / alarmas tempranas)", "Crítica", "Disp. sistema +1.5%", 0, 12000, "Gran Tierra", "En curso", true, "Disponibilidad <98%"),
        rec(p4, 2, "Programa de mantenimiento preventivo semanal formal", "Crítica", "Fallas -45%", 0, 6000, "Gran Tierra", "Abierta", true, "≥3 fallas / impacto sistémico"),
        rec(p4, 3, "Optimizar procedimiento operativo post-NGL", "Alta", "MTTR -20%", 2, 1500, "Operación GTE", "Abierta", false),
      ],
    }),
    plan({
      id: p5,
      assetId: "CPW05",
      assetName: "CPW05",
      equipmentType: "Gobernador",
      manufacturer: "Woodward / CAT",
      criticality: "Alta",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 1000 h",
      recommendedStrategy: "RCM",
      recommendedFrequency: "Cada 750 h + prueba load sharing",
      optimizationStatus: "Requiere optimización",
      expectedBenefit: "Estabilizar reparto de carga post-MRU",
      benefits: { mtbfPct: 15, availabilityPct: 0.5, mttrPct: -12, costPct: -1, failuresPct: -30 },
      operatingHours: 699,
      availabilityPct: 98.89,
      mtbfHours: 699,
      mttrHours: 1,
      failures: 1,
      maintenanceCostUsd: 7600,
      outageHours: 1,
      impactIndex: 6.8,
      linkedRcaIds: ["RCA-005"],
      linkedPlanIds: ["IP-GTE-005"],
      linkedEventHints: ["Potencia inversa 28-jun"],
      justification:
        "Tras salida de MRU se observó redistribución súbita de carga (RCA-005). El intervalo de 1000 h en gobernación/load sharing es insuficiente frente a transitorios del parque. Se recomienda enfoque RCM con prueba de load sharing cada 750 h.",
      recommendations: [
        rec(p5, 1, "Acortar frecuencia de revisión de load sharing 1000 h → 750 h", "Alta", "Fallas -30%", 1, 2000, "Instrumentación", "Abierta", true, "Índice de impacto >6"),
        rec(p5, 2, "Calibración de gobernadores post-evento MRU", "Alta", "MTBF +15%", 1, 1800, "Instrumentación", "Implementada", false),
      ],
    }),
    plan({
      id: p6,
      assetId: "CPW07",
      assetName: "CPW07",
      equipmentType: "AVR",
      manufacturer: "Basler / CAT",
      criticality: "Alta",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 2000 h",
      recommendedStrategy: "Basado en Condición",
      recommendedFrequency: "Tras perturbación + trimestral",
      optimizationStatus: "En aprobación",
      expectedBenefit: "Mejor respuesta ante perturbaciones de red",
      benefits: { mtbfPct: 10, availabilityPct: 0.4, mttrPct: -5, costPct: 0, failuresPct: -20 },
      operatingHours: 605,
      availabilityPct: 99.31,
      mtbfHours: 605,
      mttrHours: 5,
      failures: 1,
      maintenanceCostUsd: 5400,
      outageHours: 5,
      impactIndex: 5.8,
      linkedRcaIds: ["RCA-004"],
      linkedPlanIds: ["IP-GTE-004"],
      linkedEventHints: ["Perturbación eléctrica 27-jun"],
      justification:
        "El evento del 27-jun fue de origen externo (RCA-004), pero el AVR y protecciones deben verificarse por condición tras cada perturbación. Mantener preventivo largo sin revisión post-evento no agrega valor; se recomienda trigger por evento + chequeo trimestral.",
      recommendations: [
        rec(p6, 1, "Verificación AVR / protecciones tras perturbación de red", "Alta", "MTTR -5%", 0, 900, "Eléctrico", "Abierta", true, "RCA de red / misma familia"),
        rec(p6, 2, "Validación de sincronismo trimestral", "Media", "Estabilidad eléctrica", 1, 700, "Eléctrico", "Abierta", false),
      ],
    }),
    plan({
      id: p7,
      assetId: "CPW02",
      assetName: "CPW02",
      equipmentType: "Motor",
      manufacturer: "Caterpillar",
      criticality: "Media",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 250 h",
      recommendedStrategy: "Preventivo",
      recommendedFrequency: "Cada 500 h",
      optimizationStatus: "Validado",
      expectedBenefit: "Reducir sobre-mantenimiento sin degradar confiabilidad",
      benefits: { mtbfPct: 0, availabilityPct: 0.1, mttrPct: 0, costPct: -12, failuresPct: 0 },
      operatingHours: 652,
      availabilityPct: 100,
      mtbfHours: null,
      mttrHours: 0,
      failures: 0,
      maintenanceCostUsd: 11200,
      outageHours: 0,
      impactIndex: 1.2,
      linkedRcaIds: [],
      linkedPlanIds: [],
      linkedEventHints: ["Sin fallas contractuales en junio"],
      justification:
        "CPW02 cerró junio sin fallas y con disponibilidad 100%. La frecuencia actual (250 h) sugiere sobre-mantenimiento: se propone extender a 500 h alineado al estándar del parque, liberando capacidad de mantenimiento sin aumentar riesgo.",
      recommendations: [
        rec(p7, 1, "Extender frecuencia preventiva 250 h → 500 h", "Media", "Costo -12%", 12, 0, "Confiabilidad", "Implementada", true, "Sin fallas + alta disponibilidad"),
        rec(p7, 2, "Eliminar actividad redundante de inspección intermedia", "Baja", "Horas-hombre -8%", 8, 0, "Mecánico", "Implementada", false),
      ],
    }),
    plan({
      id: p8,
      assetId: "CPW04",
      assetName: "CPW04",
      equipmentType: "Radiador",
      manufacturer: "Caterpillar",
      criticality: "Media",
      currentStrategy: "Preventivo",
      currentFrequency: "Cada 1000 h",
      recommendedStrategy: "Basado en Condición",
      recommendedFrequency: "Por temperatura diferencial",
      optimizationStatus: "Pendiente análisis",
      expectedBenefit: "Mantener enfriamiento sin PM excesivo",
      benefits: { mtbfPct: 5, availabilityPct: 0.2, mttrPct: -4, costPct: -6, failuresPct: -10 },
      operatingHours: 708,
      availabilityPct: 100,
      mtbfHours: null,
      mttrHours: 0,
      failures: 0,
      maintenanceCostUsd: 6100,
      outageHours: 0,
      impactIndex: 1.5,
      linkedRcaIds: [],
      linkedPlanIds: [],
      linkedEventHints: ["Salida imputada a cliente (no contractual)"],
      justification:
        "Sin fallas contractuales en junio. El radiador puede migrar a mantenimiento por condición (ΔT) en lugar de intervalo fijo de 1000 h, reduciendo intervenciones de bajo valor.",
      recommendations: [
        rec(p8, 1, "Migrar limpieza de radiador a criterio por ΔT", "Media", "Costo -6%", 6, 1100, "Mecánico", "Abierta", false),
        rec(p8, 2, "Agregar inspección termográfica de banco de radiadores", "Baja", "Detección temprana", 2, 800, "Predictivo", "Abierta", false),
      ],
    }),
  ];
}

export function strategyMix(plans: MaintenanceOptimizationPlan[]) {
  const counts = new Map<MaintenanceStrategy, number>();
  for (const p of plans) {
    counts.set(p.recommendedStrategy, (counts.get(p.recommendedStrategy) ?? 0) + 1);
  }
  const total = plans.length || 1;
  return [...counts.entries()]
    .map(([name, count]) => ({ name, count, pct: Math.round((count / total) * 100) }))
    .sort((a, b) => b.count - a.count);
}

export function topOpportunities(plans: MaintenanceOptimizationPlan[], limit = 4) {
  return [...plans]
    .filter((p) => p.healthBand !== "Excelente" || p.optimizationStatus === "Requiere optimización")
    .sort((a, b) => a.mphi - b.mphi || b.impactIndex - a.impactIndex)
    .slice(0, limit)
    .map((p) => ({
      assetId: p.assetId,
      action: p.recommendations[0]?.recommendation ?? p.expectedBenefit,
      stars: p.impactIndex >= 8 ? 5 : p.impactIndex >= 6 ? 4 : p.impactIndex >= 4 ? 3 : 2,
      mphi: p.mphi,
    }));
}

export function portfolioKpis(plans: MaintenanceOptimizationPlan[]) {
  const optimized = plans.filter(
    (p) => p.optimizationStatus === "Implementado" || p.optimizationStatus === "Validado",
  ).length;
  const avgCostSaving =
    plans.reduce((acc, p) => acc + Math.abs(Math.min(0, p.benefits.costPct)), 0) /
    (plans.length || 1);
  const avgAvailGain =
    plans.reduce((acc, p) => acc + p.benefits.availabilityPct, 0) / (plans.length || 1);
  const avgFailDrop =
    plans.reduce((acc, p) => acc + Math.abs(p.benefits.failuresPct), 0) / (plans.length || 1);
  return {
    assetsAnalyzed: plans.length,
    plansEvaluated: plans.length,
    plansOptimized: optimized,
    estimatedSavingsPct: Number(avgCostSaving.toFixed(1)),
    expectedAvailabilityGain: Number(avgAvailGain.toFixed(2)),
    expectedFailureReduction: Math.round(avgFailDrop),
  };
}
