/** Generado por scripts/etl-inventario.mjs — no editar a mano. */
export type InventoryMinItem = {
  id: string;
  family: string;
  description: string;
  status: string;
  /** Mínimo requerido (heredado del catálogo previo por P/N). */
  stockMin: number;
  /** STOCK del kardex — cantidad actual en bodega. */
  onHand: number;
  partNumber: string;
  received: number;
  issued: number;
  review: boolean;
};

export type InventoryMovement = {
  kind: "entrada" | "salida";
  date: string;
  partNumber: string;
  description: string;
  qty: number;
};

export type InventoryMinPack = {
  sourceFile: string;
  sheet: string;
  extractedAt: string;
  notes: string;
  items: InventoryMinItem[];
  movements: InventoryMovement[];
};

export const INVENTORY_MINIMUMS: InventoryMinPack = {
  "sourceFile": "data/Agosto/INVENTARIO FINAL BODEGA COSTAYACO.xlsx",
  "sheet": "Hoja1",
  "extractedAt": "2026-09-01",
  "notes": "Cierre bodega Costayaco. STOCK = existencia actual. ENTRADAS/SALIDAS del kardex. Mínimo heredado del catálogo previo por P/N.",
  "items": [
    {
      "id": "INV-0001",
      "family": "J320",
      "description": "filtro de aire j320",
      "status": "BUENO",
      "stockMin": 11,
      "onHand": 11,
      "partNumber": "1023529A",
      "received": 11,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0002",
      "family": "J320",
      "description": "filtro aire j320",
      "status": "BUENO",
      "stockMin": 5,
      "onHand": 5,
      "partNumber": "464424",
      "received": 5,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0003",
      "family": "J420",
      "description": "filtro aire j420",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "1237578",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0004",
      "family": "J420",
      "description": "filtro aceite j420",
      "status": "BAJO",
      "stockMin": 3,
      "onHand": 1,
      "partNumber": "245488",
      "received": 3,
      "issued": 2,
      "review": false
    },
    {
      "id": "INV-0005",
      "family": "JINAN",
      "description": "filtro aceite jinan",
      "status": "BAJO",
      "stockMin": 72,
      "onHand": 52,
      "partNumber": "12VB1810B",
      "received": 72,
      "issued": 20,
      "review": false
    },
    {
      "id": "INV-0006",
      "family": "J420",
      "description": "filtro gas entreda j420",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "217P-5M",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0007",
      "family": "J420",
      "description": "filtro interno de aire 06 j420",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 3,
      "partNumber": "1227732",
      "received": 6,
      "issued": 3,
      "review": false
    },
    {
      "id": "INV-0008",
      "family": "JINAN",
      "description": "valvula culata de admision jinan",
      "status": "BUENO",
      "stockMin": 56,
      "onHand": 56,
      "partNumber": "12VB0337",
      "received": 56,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0009",
      "family": "JINAN",
      "description": "valvula culata de escape jinan",
      "status": "BUENO",
      "stockMin": 52,
      "onHand": 52,
      "partNumber": "12VB0322",
      "received": 52,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0010",
      "family": "JINAN",
      "description": "asiento culata admision jinan",
      "status": "BUENO",
      "stockMin": 97,
      "onHand": 97,
      "partNumber": "127038004",
      "received": 97,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0011",
      "family": "JINAN",
      "description": "asiento culata escape jinan",
      "status": "BUENO",
      "stockMin": 104,
      "onHand": 104,
      "partNumber": "127038005",
      "received": 104,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0012",
      "family": "JINAN",
      "description": "camisa de piston jinan",
      "status": "BUENO",
      "stockMin": 11,
      "onHand": 11,
      "partNumber": "12V0102C",
      "received": 11,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0013",
      "family": "J320",
      "description": "motor de arranque j320",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "1201862",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0014",
      "family": "J320",
      "description": "motor de arranque REPARADO j320",
      "status": "BAJO",
      "stockMin": 3,
      "onHand": 2,
      "partNumber": "1238548",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0015",
      "family": "JINAN",
      "description": "motor de arranque jinan",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "12VB4603",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0016",
      "family": "J420",
      "description": "hidroflow j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "102268",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0017",
      "family": "MATERIALES",
      "description": "valvula medenus",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0018",
      "family": "MATERIALES",
      "description": "baterias 8d",
      "status": "REVISIÓN",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "—",
      "received": 3,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0019",
      "family": "MATERIALES",
      "description": "cinta multiusos autoadhesiva viaflexfita",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "—",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0020",
      "family": "J420",
      "description": "termocuplas j320",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 9,
      "partNumber": "550401",
      "received": 9,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0021",
      "family": "J420",
      "description": "termocuplas j420",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 34,
      "partNumber": "550401",
      "received": 34,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0022",
      "family": "J320",
      "description": "fuente de bateria j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0023",
      "family": "SIN CLASIFICAR",
      "description": "baterias 12 v",
      "status": "BUENO",
      "stockMin": 7,
      "onHand": 7,
      "partNumber": "SLA127",
      "received": 8,
      "issued": 1,
      "review": false
    },
    {
      "id": "INV-0024",
      "family": "J320",
      "description": "camisas de piston j320",
      "status": "BUENO",
      "stockMin": 5,
      "onHand": 5,
      "partNumber": "448651",
      "received": 5,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0025",
      "family": "J320",
      "description": "valvula reguladora dn80 j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0026",
      "family": "J320",
      "description": "culata j320+una de segunda",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "453448",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0027",
      "family": "SIN CLASIFICAR",
      "description": "baypass",
      "status": "REVISIÓN",
      "stockMin": 5,
      "onHand": 5,
      "partNumber": "516231",
      "received": 5,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0028",
      "family": "J320",
      "description": "biela j320",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "424942",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0029",
      "family": "J320",
      "description": "scraper ring\"anillos de fuego\" j320",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 30,
      "partNumber": "337459",
      "received": 31,
      "issued": 1,
      "review": false
    },
    {
      "id": "INV-0030",
      "family": "J320",
      "description": "rodamiento tresero j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0031",
      "family": "J320",
      "description": "rodamiento delantero j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0032",
      "family": "J420",
      "description": "juntas flexibles j420",
      "status": "BUENO",
      "stockMin": 8,
      "onHand": 8,
      "partNumber": "249011",
      "received": 8,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0033",
      "family": "J320",
      "description": "válvulas 3 vías lt j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "1207424",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0034",
      "family": "MATERIALES",
      "description": "electrobomba 1hp",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0035",
      "family": "J320",
      "description": "bomba de agua j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0036",
      "family": "MATERIALES",
      "description": "valvula de agua 1/2",
      "status": "REVISIÓN",
      "stockMin": 34,
      "onHand": 34,
      "partNumber": "—",
      "received": 34,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0037",
      "family": "MATERIALES ELÉCTRICOS",
      "description": "sensores digitales msa",
      "status": "REVISIÓN",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "MATERIALES ELÉCTRICOS",
      "received": 2,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0038",
      "family": "SIN CLASIFICAR",
      "description": "control de nivel",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "15700759",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0039",
      "family": "J320",
      "description": "filtro aceite j320",
      "status": "BAJO",
      "stockMin": 22,
      "onHand": 19,
      "partNumber": "225125",
      "received": 22,
      "issued": 3,
      "review": false
    },
    {
      "id": "INV-0040",
      "family": "J420",
      "description": "filtro de gas entrada j420",
      "status": "BUENO",
      "stockMin": 14,
      "onHand": 14,
      "partNumber": "—",
      "received": 15,
      "issued": 1,
      "review": false
    },
    {
      "id": "INV-0041",
      "family": "J320",
      "description": "filtro aceite prelubricacion j320",
      "status": "BUENO",
      "stockMin": 11,
      "onHand": 11,
      "partNumber": "235027",
      "received": 11,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0042",
      "family": "JINAN",
      "description": "filtro de gas jinan",
      "status": "BUENO",
      "stockMin": 7,
      "onHand": 7,
      "partNumber": "—",
      "received": 10,
      "issued": 3,
      "review": false
    },
    {
      "id": "INV-0043",
      "family": "JINAN",
      "description": "bujías jinan",
      "status": "BUENO",
      "stockMin": 15,
      "onHand": 15,
      "partNumber": "—",
      "received": 15,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0044",
      "family": "J320",
      "description": "bobina j320 dañada",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0045",
      "family": "J320",
      "description": "oring sellos culata j320",
      "status": "BUENO",
      "stockMin": 124,
      "onHand": 148,
      "partNumber": "1251252",
      "received": 148,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0046",
      "family": "J320",
      "description": "gasket bomba de alta descarga j320",
      "status": "BAJO",
      "stockMin": 18,
      "onHand": 12,
      "partNumber": "505738",
      "received": 12,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0047",
      "family": "J320",
      "description": "gasket flauta de agua a culata j320",
      "status": "BUENO",
      "stockMin": 13,
      "onHand": 30,
      "partNumber": "100875",
      "received": 30,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0048",
      "family": "J320",
      "description": "gasket tapa valvulas j320",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 85,
      "partNumber": "100548",
      "received": 85,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0049",
      "family": "J320",
      "description": "oring manifold admision j320",
      "status": "BUENO",
      "stockMin": 7,
      "onHand": 7,
      "partNumber": "102131",
      "received": 7,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0050",
      "family": "J320",
      "description": "eje valvula throttle j320",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "234272",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0051",
      "family": "J320",
      "description": "perno de biela j320",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "379058",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0052",
      "family": "J320",
      "description": "balancín de admision j320",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "242329",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0053",
      "family": "J320",
      "description": "balancín de escape j320",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "242328",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0054",
      "family": "J320",
      "description": "accesorios actuador j320",
      "status": "BUENO",
      "stockMin": 13,
      "onHand": 13,
      "partNumber": "1101733",
      "received": 13,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0055",
      "family": "J320",
      "description": "empaque múltiple admisión j320",
      "status": "BUENO",
      "stockMin": 20,
      "onHand": 20,
      "partNumber": "—",
      "received": 20,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0056",
      "family": "SIN CLASIFICAR",
      "description": "empaque múltiple de escape",
      "status": "AGOTADO",
      "stockMin": 1,
      "onHand": 0,
      "partNumber": "—",
      "received": 9,
      "issued": 9,
      "review": false
    },
    {
      "id": "INV-0057",
      "family": "J320",
      "description": "casquete de biela j320 x2",
      "status": "BAJO",
      "stockMin": 2,
      "onHand": 1,
      "partNumber": "482681",
      "received": 2,
      "issued": 1,
      "review": false
    },
    {
      "id": "INV-0058",
      "family": "J320",
      "description": "gasket junta de culata j320",
      "status": "BUENO",
      "stockMin": 7,
      "onHand": 43,
      "partNumber": "448657",
      "received": 43,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0059",
      "family": "J320",
      "description": "termostato j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "321540",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0060",
      "family": "J320",
      "description": "enfocador j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0061",
      "family": "J320",
      "description": "filtro niebla j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 3,
      "partNumber": "9010789",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0062",
      "family": "J320",
      "description": "compensator j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "105174",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0063",
      "family": "J420",
      "description": "arandelas bujías j420",
      "status": "BUENO",
      "stockMin": 188,
      "onHand": 188,
      "partNumber": "102981",
      "received": 188,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0064",
      "family": "J420",
      "description": "bujías j420 usadas",
      "status": "BAJO",
      "stockMin": 20,
      "onHand": 9,
      "partNumber": "1254664",
      "received": 9,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0065",
      "family": "J420",
      "description": "coupling j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "334304",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0066",
      "family": "J420",
      "description": "puente de culata j420",
      "status": "BUENO",
      "stockMin": 8,
      "onHand": 8,
      "partNumber": "21993199",
      "received": 8,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0067",
      "family": "J420",
      "description": "tuerca espárragos culata j420",
      "status": "BUENO",
      "stockMin": 7,
      "onHand": 7,
      "partNumber": "291723",
      "received": 7,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0068",
      "family": "J420",
      "description": "tuerca balancín j420",
      "status": "BUENO",
      "stockMin": 8,
      "onHand": 8,
      "partNumber": "101823",
      "received": 8,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0069",
      "family": "J420",
      "description": "tuerca tornillo regulador j420",
      "status": "BUENO",
      "stockMin": 12,
      "onHand": 12,
      "partNumber": "113807",
      "received": 12,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0070",
      "family": "J420",
      "description": "perno de ajuste puente culata j420",
      "status": "BUENO",
      "stockMin": 12,
      "onHand": 12,
      "partNumber": "281881",
      "received": 12,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0071",
      "family": "J420",
      "description": "tuerca balancin j420",
      "status": "BUENO",
      "stockMin": 12,
      "onHand": 12,
      "partNumber": "161400",
      "received": 12,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0072",
      "family": "J420",
      "description": "tornillo de regulación balancin j420",
      "status": "BUENO",
      "stockMin": 8,
      "onHand": 8,
      "partNumber": "121209",
      "received": 8,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0073",
      "family": "J420",
      "description": "anillos de fuego j420",
      "status": "BUENO",
      "stockMin": 10,
      "onHand": 10,
      "partNumber": "448559",
      "received": 10,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0074",
      "family": "J420",
      "description": "biela j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "11020200",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0075",
      "family": "J420",
      "description": "rodamiento de alternador india j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "GA-251711",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0076",
      "family": "J420",
      "description": "perno de biela j420",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "1103091",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0077",
      "family": "MATERIALES",
      "description": "manguera metálica flexibles",
      "status": "REVISIÓN",
      "stockMin": 6,
      "onHand": 6,
      "partNumber": "—",
      "received": 6,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0078",
      "family": "J420",
      "description": "camisas j420",
      "status": "BUENO",
      "stockMin": 5,
      "onHand": 5,
      "partNumber": "448556",
      "received": 5,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0079",
      "family": "J420",
      "description": "scrape ring j420",
      "status": "BUENO",
      "stockMin": 40,
      "onHand": 60,
      "partNumber": "421782",
      "received": 60,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0080",
      "family": "J320",
      "description": "motor de arranque j320",
      "status": "BAJO",
      "stockMin": 3,
      "onHand": 1,
      "partNumber": "1238548",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0081",
      "family": "J420",
      "description": "piston 12.5 j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "1102352",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0082",
      "family": "J420",
      "description": "gasket múltiple de escape j420",
      "status": "BUENO",
      "stockMin": 20,
      "onHand": 20,
      "partNumber": "7001950",
      "received": 20,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0083",
      "family": "J420",
      "description": "gasket múltiple de escape j420",
      "status": "BUENO",
      "stockMin": 20,
      "onHand": 20,
      "partNumber": "306099",
      "received": 20,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0084",
      "family": "J420",
      "description": "o-ring regulador oil j420",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "456731",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0085",
      "family": "J420",
      "description": "gasket riel tubería agua j420",
      "status": "BUENO",
      "stockMin": 97,
      "onHand": 97,
      "partNumber": "290213",
      "received": 97,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0086",
      "family": "J420",
      "description": "o-ring camisas j420",
      "status": "BUENO",
      "stockMin": 56,
      "onHand": 56,
      "partNumber": "348964",
      "received": 56,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0087",
      "family": "J420",
      "description": "o-ring j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "319742",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0088",
      "family": "J420",
      "description": "o-ring culatin j420",
      "status": "BUENO",
      "stockMin": 18,
      "onHand": 18,
      "partNumber": "456732",
      "received": 18,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0089",
      "family": "J420",
      "description": "transformador de medicion j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "415442",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0090",
      "family": "J420",
      "description": "o-ring de admision j420",
      "status": "BUENO",
      "stockMin": 5,
      "onHand": 5,
      "partNumber": "456747",
      "received": 5,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0091",
      "family": "J420",
      "description": "empaques exosto j420",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 10,
      "partNumber": "107744",
      "received": 10,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0092",
      "family": "J420",
      "description": "culata equipo g56 j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "1247730",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0093",
      "family": "MATERIALES ELÉCTRICOS",
      "description": "motor eléctrico alto rendimiento",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "85U07417",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0094",
      "family": "J420",
      "description": "engranajes árbol levas j420",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "9013876",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0095",
      "family": "J420",
      "description": "biela j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "22355251",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0096",
      "family": "J420",
      "description": "empaque intercooler j420",
      "status": "BAJO",
      "stockMin": 12,
      "onHand": 9,
      "partNumber": "303923",
      "received": 9,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0097",
      "family": "J420",
      "description": "switch de nivel j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "1252080",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0098",
      "family": "J420",
      "description": "balancín de admision j420",
      "status": "BUENO",
      "stockMin": 5,
      "onHand": 5,
      "partNumber": "276617",
      "received": 5,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0099",
      "family": "J420",
      "description": "chavetas bulón piston j420",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "277937",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0100",
      "family": "J420",
      "description": "anillos de compresion j420",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "372382",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0101",
      "family": "J420",
      "description": "anillos lubricación j420",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "525691",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0102",
      "family": "J420",
      "description": "anillos rascador j420",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "574332",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0103",
      "family": "J420",
      "description": "arandelas de bronce j420",
      "status": "BUENO",
      "stockMin": 20,
      "onHand": 20,
      "partNumber": "100639",
      "received": 20,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0104",
      "family": "SIN CLASIFICAR",
      "description": "arandelas axiales cigueñal",
      "status": "REVISIÓN",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "344227",
      "received": 4,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0105",
      "family": "J420",
      "description": "bujes de biela j420",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "277872",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0106",
      "family": "J420",
      "description": "tornillo de ajuste rociadorj420",
      "status": "BUENO",
      "stockMin": 20,
      "onHand": 20,
      "partNumber": "101363",
      "received": 20,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0107",
      "family": "J420",
      "description": "o-ring rociador piñoneria de reparticion j420",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "456748",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0108",
      "family": "J420",
      "description": "rociador aceite piñoneria reparticion j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "9014144",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0109",
      "family": "MATERIALES",
      "description": "manguera de alta presión 2\"",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0110",
      "family": "J420",
      "description": "alternador j420",
      "status": "BAJO",
      "stockMin": 2,
      "onHand": 1,
      "partNumber": "326960",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0111",
      "family": "J420",
      "description": "empaque carter j420",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "352496",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0112",
      "family": "J420",
      "description": "empaque carter j420",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "352495",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0113",
      "family": "J420",
      "description": "empaque carter j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "352954",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0114",
      "family": "J420",
      "description": "empaque carter j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "352953",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0115",
      "family": "J420",
      "description": "oring salida carter j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "302612",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0116",
      "family": "J420",
      "description": "oring tapa filtros oil j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 2,
      "partNumber": "162817",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0117",
      "family": "J420",
      "description": "oring tubería de aguaj420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 3,
      "partNumber": "468727",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0118",
      "family": "J420",
      "description": "oring de admision j420",
      "status": "BUENO",
      "stockMin": 20,
      "onHand": 20,
      "partNumber": "225040",
      "received": 20,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0119",
      "family": "J420",
      "description": "gasket by-past j420",
      "status": "BUENO",
      "stockMin": 7,
      "onHand": 7,
      "partNumber": "107725",
      "received": 7,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0120",
      "family": "J420",
      "description": "oring by-past j420",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "301384",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0121",
      "family": "J420",
      "description": "oring by-past j420",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "323220",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0122",
      "family": "J420",
      "description": "bulón de piston j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "1102429",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0123",
      "family": "JINAN",
      "description": "chavetas de seguridad jinan",
      "status": "AGOTADO",
      "stockMin": 1,
      "onHand": 0,
      "partNumber": "1101290",
      "received": 0,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0124",
      "family": "J420",
      "description": "termostato j420",
      "status": "AGOTADO",
      "stockMin": 1,
      "onHand": 0,
      "partNumber": "282904",
      "received": 0,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0125",
      "family": "J320",
      "description": "empaque bomba agua ht j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 6,
      "partNumber": "103143",
      "received": 6,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0126",
      "family": "J420",
      "description": "filtro de aire j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "1227733",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0127",
      "family": "J420",
      "description": "gasket bomba recirculación agua j420",
      "status": "BUENO",
      "stockMin": 11,
      "onHand": 11,
      "partNumber": "100606",
      "received": 11,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0128",
      "family": "J420",
      "description": "oring valvulas j420",
      "status": "BUENO",
      "stockMin": 60,
      "onHand": 60,
      "partNumber": "456737",
      "received": 60,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0129",
      "family": "J420",
      "description": "oring asiento de turbo j420",
      "status": "BUENO",
      "stockMin": 16,
      "onHand": 16,
      "partNumber": "376511",
      "received": 16,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0130",
      "family": "SIN CLASIFICAR",
      "description": "oring",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "236907",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0131",
      "family": "J420",
      "description": "oring j420",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "513686",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0132",
      "family": "J420",
      "description": "oring j420",
      "status": "BUENO",
      "stockMin": 6,
      "onHand": 6,
      "partNumber": "513685",
      "received": 6,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0133",
      "family": "J420",
      "description": "super empaque carter j420",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "—",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0134",
      "family": "SIN CLASIFICAR",
      "description": "actuador de valvula con posicionador",
      "status": "REVISIÓN",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "—",
      "received": 2,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0135",
      "family": "J320",
      "description": "actuador j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "8404213",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0136",
      "family": "J420",
      "description": "bomba de agua ht j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "1204119",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0137",
      "family": "J420",
      "description": "casquete de biela j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "351228",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0138",
      "family": "SIN CLASIFICAR",
      "description": "valvula magnetica",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "659643",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0139",
      "family": "J320",
      "description": "casquete bulón biela j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "190308",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0140",
      "family": "MATERIALES",
      "description": "prefiltros o guatas",
      "status": "AGOTADO",
      "stockMin": 1,
      "onHand": 0,
      "partNumber": "—",
      "received": 2,
      "issued": 2,
      "review": true
    },
    {
      "id": "INV-0141",
      "family": "JINAN",
      "description": "guías puente valvulas jinan",
      "status": "BAJO",
      "stockMin": 30,
      "onHand": 29,
      "partNumber": "12VB037001",
      "received": 30,
      "issued": 1,
      "review": false
    },
    {
      "id": "INV-0142",
      "family": "JINAN",
      "description": "resorte grande culata jinan",
      "status": "BUENO",
      "stockMin": 32,
      "onHand": 32,
      "partNumber": "Z12V0318A",
      "received": 32,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0143",
      "family": "JINAN",
      "description": "resorte pequeño culata jinan",
      "status": "BUENO",
      "stockMin": 57,
      "onHand": 57,
      "partNumber": "Z12V0317A",
      "received": 57,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0144",
      "family": "SIN CLASIFICAR",
      "description": "asiento valancin",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "12VB031005A",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0145",
      "family": "JINAN",
      "description": "esparragos pequeños jinan",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "1002510",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0146",
      "family": "JINAN",
      "description": "termocuplas jinan",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0147",
      "family": "JINAN",
      "description": "chavetas o keepers de valvula jinan",
      "status": "BUENO",
      "stockMin": 80,
      "onHand": 80,
      "partNumber": "12V0316A",
      "received": 80,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0148",
      "family": "SIN CLASIFICAR",
      "description": "sellos valvula culata",
      "status": "REVISIÓN",
      "stockMin": 15,
      "onHand": 15,
      "partNumber": "—",
      "received": 15,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0149",
      "family": "JINAN",
      "description": "gasket tubería agua culata jinan",
      "status": "BAJO",
      "stockMin": 16,
      "onHand": 9,
      "partNumber": "12VB2407",
      "received": 16,
      "issued": 7,
      "review": false
    },
    {
      "id": "INV-0150",
      "family": "JINAN",
      "description": "anillo cobre asiento culata jinan",
      "status": "BUENO",
      "stockMin": 16,
      "onHand": 16,
      "partNumber": "12VB0103",
      "received": 16,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0151",
      "family": "J320",
      "description": "gasket salida turbo j320",
      "status": "BUENO",
      "stockMin": 14,
      "onHand": 14,
      "partNumber": "268630",
      "received": 14,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0152",
      "family": "J320",
      "description": "tornillo de regulación balancin j320",
      "status": "BUENO",
      "stockMin": 18,
      "onHand": 18,
      "partNumber": "100653",
      "received": 18,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0153",
      "family": "J420",
      "description": "gasket múltiple escape salida j420",
      "status": "BAJO",
      "stockMin": 6,
      "onHand": 4,
      "partNumber": "356298",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0154",
      "family": "J420",
      "description": "arandelas bronce intercooler j420",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "100834",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0155",
      "family": "J420",
      "description": "oring tubería refrigeracion j420",
      "status": "BUENO",
      "stockMin": 6,
      "onHand": 6,
      "partNumber": "100017",
      "received": 6,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0156",
      "family": "JINAN",
      "description": "gasket asiento sleeve jinan",
      "status": "BAJO",
      "stockMin": 10,
      "onHand": 5,
      "partNumber": "1270303",
      "received": 10,
      "issued": 5,
      "review": false
    },
    {
      "id": "INV-0157",
      "family": "JINAN",
      "description": "tornillo regulación balancin jinan",
      "status": "BUENO",
      "stockMin": 65,
      "onHand": 65,
      "partNumber": "12VB0390B",
      "received": 65,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0158",
      "family": "JINAN",
      "description": "gasket múltiple escape jinan",
      "status": "BUENO",
      "stockMin": 13,
      "onHand": 13,
      "partNumber": "Z12VB0904B",
      "received": 13,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0159",
      "family": "JINAN",
      "description": "gasket tapa valvulas jinan",
      "status": "BUENO",
      "stockMin": 23,
      "onHand": 23,
      "partNumber": "12VB032006B",
      "received": 23,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0160",
      "family": "J420",
      "description": "flexible turbo j420",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "351248",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0161",
      "family": "SIN CLASIFICAR",
      "description": "gasket tuberías 2\"1/2",
      "status": "BUENO",
      "stockMin": 13,
      "onHand": 13,
      "partNumber": "—",
      "received": 13,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0162",
      "family": "SIN CLASIFICAR",
      "description": "gasket tubería 4\"",
      "status": "BUENO",
      "stockMin": 14,
      "onHand": 14,
      "partNumber": "—",
      "received": 14,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0163",
      "family": "SIN CLASIFICAR",
      "description": "gasket tubería 1\"1/2",
      "status": "BUENO",
      "stockMin": 8,
      "onHand": 8,
      "partNumber": "—",
      "received": 8,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0164",
      "family": "SIN CLASIFICAR",
      "description": "gasket tubería 3\"",
      "status": "BUENO",
      "stockMin": 20,
      "onHand": 20,
      "partNumber": "—",
      "received": 20,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0165",
      "family": "SIN CLASIFICAR",
      "description": "valvula control combustible",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "21389452",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0166",
      "family": "SIN CLASIFICAR",
      "description": "bomba carcasa de agua",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "3098964",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0167",
      "family": "J420",
      "description": "reten cigüeñal delantero j320-j420",
      "status": "BUENO",
      "stockMin": 12,
      "onHand": 12,
      "partNumber": "395571",
      "received": 12,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0168",
      "family": "SIN CLASIFICAR",
      "description": "gasket escape salida turbo",
      "status": "REVISIÓN",
      "stockMin": 8,
      "onHand": 8,
      "partNumber": "100099",
      "received": 8,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0169",
      "family": "J320",
      "description": "flexibles salida escape j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "23824",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0170",
      "family": "J420",
      "description": "bomba prelubricacion j420",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "1247616",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0171",
      "family": "MATERIALES",
      "description": "manguera 1\" bar1262",
      "status": "REVISIÓN",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "—",
      "received": 3,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0172",
      "family": "MATERIALES",
      "description": "manguera 3/4 bar1523",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "—",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0173",
      "family": "MATERIALES",
      "description": "mangueras varias",
      "status": "REVISIÓN",
      "stockMin": 5,
      "onHand": 5,
      "partNumber": "—",
      "received": 5,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0174",
      "family": "SIN CLASIFICAR",
      "description": "manometro presión",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "E7593-2-2",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0175",
      "family": "SIN CLASIFICAR",
      "description": "kit de calibración",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0176",
      "family": "J420",
      "description": "switch de nivel",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "1252080",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0177",
      "family": "SIN CLASIFICAR",
      "description": "manómetro transformadores presión baja",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "—",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0178",
      "family": "SIN CLASIFICAR",
      "description": "manómetros de presion",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "PFQ803",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0179",
      "family": "SIN CLASIFICAR",
      "description": "chaquetas",
      "status": "BUENO",
      "stockMin": 12,
      "onHand": 12,
      "partNumber": "4002777",
      "received": 12,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0180",
      "family": "JINAN",
      "description": "pickups jinan",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "—",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0181",
      "family": "SIN CLASIFICAR",
      "description": "resistencia termometro pt100",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "179609",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0182",
      "family": "SIN CLASIFICAR",
      "description": "acoples de medicion",
      "status": "BUENO",
      "stockMin": 6,
      "onHand": 6,
      "partNumber": "460138",
      "received": 6,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0183",
      "family": "JINAN",
      "description": "transductor de presion jinan",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0184",
      "family": "MATERIALES",
      "description": "reductor 1/2-3/4",
      "status": "REVISIÓN",
      "stockMin": 9,
      "onHand": 9,
      "partNumber": "—",
      "received": 9,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0185",
      "family": "SIN CLASIFICAR",
      "description": "sensor proximidad inductivo",
      "status": "BUENO",
      "stockMin": 5,
      "onHand": 5,
      "partNumber": "—",
      "received": 5,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0186",
      "family": "MATERIALES",
      "description": "conector de 1/2 npft",
      "status": "REVISIÓN",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "—",
      "received": 2,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0187",
      "family": "MATERIALES",
      "description": "extensiones npft",
      "status": "REVISIÓN",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "—",
      "received": 2,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0188",
      "family": "MATERIALES",
      "description": "niple1/8",
      "status": "REVISIÓN",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "—",
      "received": 2,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0189",
      "family": "SIN CLASIFICAR",
      "description": "valvula de control de flujo",
      "status": "REVISIÓN",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "VF06-1",
      "received": 2,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0190",
      "family": "SIN CLASIFICAR",
      "description": "regulador presión de gas",
      "status": "REVISIÓN",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "PN 40 1/4",
      "received": 4,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0191",
      "family": "MATERIALES",
      "description": "manómetro de temperatura",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0192",
      "family": "SIN CLASIFICAR",
      "description": "trotthe",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0193",
      "family": "SIN CLASIFICAR",
      "description": "repuestos mixer",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0194",
      "family": "SIN CLASIFICAR",
      "description": "valvula de bola bridada",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "F15",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0195",
      "family": "JINAN",
      "description": "gasket exosto jinan",
      "status": "BUENO",
      "stockMin": 19,
      "onHand": 19,
      "partNumber": "—",
      "received": 19,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0196",
      "family": "JINAN",
      "description": "sensor de oxigeno jinan",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0197",
      "family": "J320",
      "description": "espárrago culata j320",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "—",
      "received": 2,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0198",
      "family": "SIN CLASIFICAR",
      "description": "oring varios",
      "status": "BUENO",
      "stockMin": 395,
      "onHand": 395,
      "partNumber": "—",
      "received": 395,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0199",
      "family": "JINAN",
      "description": "oring agua camisa cilindro jinan",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "12VB01130",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0200",
      "family": "JINAN",
      "description": "sellos mecánico bomba agua jinan",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "HU21-25",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0201",
      "family": "JINAN",
      "description": "diafragma mezclador jinan",
      "status": "BUENO",
      "stockMin": 6,
      "onHand": 6,
      "partNumber": "127-3",
      "received": 6,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0202",
      "family": "JINAN",
      "description": "diafragma mezclador jinan",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "GE29721X012",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0203",
      "family": "JINAN",
      "description": "oring camisa jinan",
      "status": "BUENO",
      "stockMin": 8,
      "onHand": 8,
      "partNumber": "12V0114",
      "received": 8,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0204",
      "family": "JINAN",
      "description": "oring camisa jinan",
      "status": "BUENO",
      "stockMin": 6,
      "onHand": 6,
      "partNumber": "12VB01134",
      "received": 6,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0205",
      "family": "JINAN",
      "description": "oring tubos enfriamiento jinan",
      "status": "BUENO",
      "stockMin": 6,
      "onHand": 6,
      "partNumber": "Q/JC12003",
      "received": 6,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0206",
      "family": "JINAN",
      "description": "oring grande enfriador aceite jinan",
      "status": "BUENO",
      "stockMin": 6,
      "onHand": 6,
      "partNumber": "Q/JC12003",
      "received": 6,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0207",
      "family": "JINAN",
      "description": "oring pequeños tapa enfriador jinan",
      "status": "BUENO",
      "stockMin": 2,
      "onHand": 4,
      "partNumber": "1270308",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0208",
      "family": "SIN CLASIFICAR",
      "description": "soporte de guia tipo rodillo",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "—",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0209",
      "family": "JINAN",
      "description": "oring conexiones galería aceite jinan",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "12VB2002",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0210",
      "family": "JINAN",
      "description": "oring enfriador de aceite jinan",
      "status": "BUENO",
      "stockMin": 6,
      "onHand": 12,
      "partNumber": "Q/JC12003",
      "received": 12,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0211",
      "family": "JINAN",
      "description": "oring enfriador de aceite jinan",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "12VB2002",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0212",
      "family": "J320",
      "description": "tuercas regulador balancin j320",
      "status": "BUENO",
      "stockMin": 8,
      "onHand": 8,
      "partNumber": "101819",
      "received": 8,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0213",
      "family": "SIN CLASIFICAR",
      "description": "automático motor de arranque",
      "status": "REVISIÓN",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "—",
      "received": 3,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0214",
      "family": "JINAN",
      "description": "juntas múltiple admision jinan",
      "status": "BUENO",
      "stockMin": 9,
      "onHand": 9,
      "partNumber": "P01847",
      "received": 15,
      "issued": 6,
      "review": false
    },
    {
      "id": "INV-0215",
      "family": "JINAN",
      "description": "sellos tipo grommet jinan",
      "status": "BUENO",
      "stockMin": 159,
      "onHand": 159,
      "partNumber": "—",
      "received": 183,
      "issued": 24,
      "review": false
    },
    {
      "id": "INV-0216",
      "family": "JINAN",
      "description": "sellos de valvula jinan",
      "status": "BUENO",
      "stockMin": 66,
      "onHand": 66,
      "partNumber": "—",
      "received": 66,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0217",
      "family": "SIN CLASIFICAR",
      "description": "tubo porta bujias",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0218",
      "family": "SIN CLASIFICAR",
      "description": "esparragos",
      "status": "REVISIÓN",
      "stockMin": 10,
      "onHand": 10,
      "partNumber": "—",
      "received": 10,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0219",
      "family": "SIN CLASIFICAR",
      "description": "guías lisas",
      "status": "REVISIÓN",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "—",
      "received": 2,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0220",
      "family": "SIN CLASIFICAR",
      "description": "sombrerete de valvula",
      "status": "REVISIÓN",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "—",
      "received": 3,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0221",
      "family": "SIN CLASIFICAR",
      "description": "seguros de válvulas",
      "status": "REVISIÓN",
      "stockMin": 23,
      "onHand": 23,
      "partNumber": "—",
      "received": 23,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0222",
      "family": "JINAN",
      "description": "anillo asiento culata no bronce",
      "status": "BAJO",
      "stockMin": 16,
      "onHand": 12,
      "partNumber": "12VB0103",
      "received": 12,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0223",
      "family": "J320",
      "description": "bujías usadas j320",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "—",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0224",
      "family": "SIN CLASIFICAR",
      "description": "gorro bujías usados",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "—",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0225",
      "family": "SIN CLASIFICAR",
      "description": "abrazaderas 60-63",
      "status": "REVISIÓN",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "110908",
      "received": 4,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0226",
      "family": "SIN CLASIFICAR",
      "description": "arandelas de sellos m10",
      "status": "REVISIÓN",
      "stockMin": 10,
      "onHand": 10,
      "partNumber": "JC14033",
      "received": 10,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0227",
      "family": "SIN CLASIFICAR",
      "description": "arandelas de sellos m20",
      "status": "REVISIÓN",
      "stockMin": 10,
      "onHand": 3,
      "partNumber": "JC14033",
      "received": 3,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0228",
      "family": "JINAN",
      "description": "arandelas anchas jinan",
      "status": "BUENO",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "1100201",
      "received": 4,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0229",
      "family": "JINAN",
      "description": "anillos de compresion superior jinan",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "1222234",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0230",
      "family": "SIN CLASIFICAR",
      "description": "anillo de compresion inferior",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "1222235",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0231",
      "family": "SIN CLASIFICAR",
      "description": "anillo de lubricacion",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "1222236",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0232",
      "family": "SIN CLASIFICAR",
      "description": "arandelas de sellos m27",
      "status": "REVISIÓN",
      "stockMin": 10,
      "onHand": 1,
      "partNumber": "JC14033",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0233",
      "family": "SIN CLASIFICAR",
      "description": "sellos bomba de agua",
      "status": "REVISIÓN",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "—",
      "received": 3,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0234",
      "family": "MATERIALES",
      "description": "caja de tarros de pinturas",
      "status": "AGOTADO",
      "stockMin": 1,
      "onHand": 0,
      "partNumber": "—",
      "received": 0,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0235",
      "family": "MATERIALES",
      "description": "amarras plásticas",
      "status": "REVISIÓN",
      "stockMin": 7,
      "onHand": 7,
      "partNumber": "—",
      "received": 7,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0236",
      "family": "MATERIALES",
      "description": "galón tinner",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0237",
      "family": "SIN CLASIFICAR",
      "description": "aerosol galvanizado en frio",
      "status": "REVISIÓN",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "5-AS479",
      "received": 4,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0238",
      "family": "HERRAMIENTA",
      "description": "pistola de pulverizado",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0239",
      "family": "MATERIALES",
      "description": "espuma poliuretano",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0240",
      "family": "MATERIALES",
      "description": "desplazador de humedad",
      "status": "REVISIÓN",
      "stockMin": 4,
      "onHand": 4,
      "partNumber": "—",
      "received": 4,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0241",
      "family": "MATERIALES",
      "description": "ajustador de correas",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0242",
      "family": "SIN CLASIFICAR",
      "description": "cinta multi adeciva",
      "status": "REVISIÓN",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "7974243",
      "received": 3,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0243",
      "family": "SIN CLASIFICAR",
      "description": "manguera espiral de aire",
      "status": "REVISIÓN",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "1150-001",
      "received": 2,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0244",
      "family": "SIN CLASIFICAR",
      "description": "caja guantes industriales",
      "status": "AGOTADO",
      "stockMin": 1,
      "onHand": 0,
      "partNumber": "477549",
      "received": 0,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0245",
      "family": "HERRAMIENTA",
      "description": "gancho tensor",
      "status": "REVISIÓN",
      "stockMin": 8,
      "onHand": 8,
      "partNumber": "—",
      "received": 8,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0246",
      "family": "MATERIALES",
      "description": "kit control de derrames",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0247",
      "family": "MATERIALES ELÉCTRICOS",
      "description": "solvente industrial dieléctrico",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "SS26PI",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0248",
      "family": "J320",
      "description": "caja filtro j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "624770",
      "received": 1,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0249",
      "family": "MATERIALES",
      "description": "desengrasante industrial",
      "status": "REVISIÓN",
      "stockMin": 6,
      "onHand": 6,
      "partNumber": "—",
      "received": 10,
      "issued": 4,
      "review": true
    },
    {
      "id": "INV-0250",
      "family": "MATERIALES",
      "description": "desincrustante quimico",
      "status": "REVISIÓN",
      "stockMin": 2,
      "onHand": 2,
      "partNumber": "—",
      "received": 2,
      "issued": 1,
      "review": true
    },
    {
      "id": "INV-0251",
      "family": "MATERIALES ELÉCTRICOS",
      "description": "carreto de cable utp amarillo",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0252",
      "family": "MATERIALES ELÉCTRICOS",
      "description": "carreto de cable utp negro",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0253",
      "family": "HERRAMIENTA",
      "description": "escalera naranja",
      "status": "REVISIÓN",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": true
    },
    {
      "id": "INV-0254",
      "family": "SIN CLASIFICAR",
      "description": "bomba grundfus",
      "status": "AGOTADO",
      "stockMin": 1,
      "onHand": 0,
      "partNumber": "1232128",
      "received": 1,
      "issued": 1,
      "review": false
    },
    {
      "id": "INV-0255",
      "family": "JINAN",
      "description": "caja regulador filtro de gas jinan",
      "status": "AGOTADO",
      "stockMin": 1,
      "onHand": 0,
      "partNumber": "—",
      "received": 0,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0256",
      "family": "J320",
      "description": "tornillería múltiple de escape j320-j420",
      "status": "BUENO",
      "stockMin": 48,
      "onHand": 48,
      "partNumber": "—",
      "received": 48,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0257",
      "family": "SIN CLASIFICAR",
      "description": "mangueras cortas metalica",
      "status": "BUENO",
      "stockMin": 3,
      "onHand": 3,
      "partNumber": "—",
      "received": 3,
      "issued": 0,
      "review": false
    },
    {
      "id": "INV-0258",
      "family": "J320",
      "description": "intercooler j320",
      "status": "BUENO",
      "stockMin": 1,
      "onHand": 1,
      "partNumber": "—",
      "received": 1,
      "issued": 0,
      "review": false
    }
  ],
  "movements": [
    {
      "kind": "entrada",
      "date": "2006-07-30",
      "partNumber": "—",
      "description": "rejillas protectoras de ventilador",
      "qty": 4
    },
    {
      "kind": "salida",
      "date": "2026-07-24",
      "partNumber": "—",
      "description": "desengrasante industrial",
      "qty": 2
    },
    {
      "kind": "entrada",
      "date": "2026-07-28",
      "partNumber": "337459",
      "description": "scraper ring",
      "qty": 20
    },
    {
      "kind": "entrada",
      "date": "2026-07-28",
      "partNumber": "448657",
      "description": "aro fuego culata",
      "qty": 20
    },
    {
      "kind": "salida",
      "date": "2026-07-28",
      "partNumber": "—",
      "description": "prefiltros o guatas",
      "qty": 2
    },
    {
      "kind": "entrada",
      "date": "2026-07-30",
      "partNumber": "—",
      "description": "baterias plus 8d-1600 usadas",
      "qty": 3
    },
    {
      "kind": "entrada",
      "date": "2026-07-30",
      "partNumber": "—",
      "description": "motobombas periféricas 0,5 y 1hp",
      "qty": 2
    },
    {
      "kind": "entrada",
      "date": "2026-07-30",
      "partNumber": "—",
      "description": "anillos de fuego usados",
      "qty": 21
    },
    {
      "kind": "entrada",
      "date": "2026-07-30",
      "partNumber": "—",
      "description": "aspas de ventilador en aluminio",
      "qty": 4
    },
    {
      "kind": "entrada",
      "date": "2026-07-30",
      "partNumber": "—",
      "description": "culata usada j320",
      "qty": 1
    },
    {
      "kind": "entrada",
      "date": "2026-07-30",
      "partNumber": "—",
      "description": "brazo basculante",
      "qty": 1
    },
    {
      "kind": "entrada",
      "date": "2026-07-30",
      "partNumber": "—",
      "description": "camisa cilíndrica",
      "qty": 1
    },
    {
      "kind": "entrada",
      "date": "2026-07-30",
      "partNumber": "—",
      "description": "filtros de aire 06",
      "qty": 4
    },
    {
      "kind": "entrada",
      "date": "2026-07-30",
      "partNumber": "337459",
      "description": "scrape ring\" anillos de fuego j320",
      "qty": 7
    },
    {
      "kind": "entrada",
      "date": "2026-07-30",
      "partNumber": "448657",
      "description": "gasket junta de culata j320",
      "qty": 16
    },
    {
      "kind": "entrada",
      "date": "2026-07-30",
      "partNumber": "100875",
      "description": "gasket flauta de agua a culata j320",
      "qty": 17
    },
    {
      "kind": "entrada",
      "date": "2026-07-30",
      "partNumber": "—",
      "description": "filtro de gas entrada jinan",
      "qty": 10
    },
    {
      "kind": "salida",
      "date": "2026-07-30",
      "partNumber": "245488",
      "description": "filtro aceite j420",
      "qty": 1
    },
    {
      "kind": "salida",
      "date": "2026-07-30",
      "partNumber": "—",
      "description": "desengrasante industrial",
      "qty": 1
    },
    {
      "kind": "salida",
      "date": "2026-07-31",
      "partNumber": "12VB1810B",
      "description": "filtro aceite jinan",
      "qty": 5
    },
    {
      "kind": "salida",
      "date": "2026-07-31",
      "partNumber": "—",
      "description": "filtro de gas entrada jinan",
      "qty": 1
    },
    {
      "kind": "salida",
      "date": "2026-07-31",
      "partNumber": "1270306",
      "description": "gasket camisa bujía jinan",
      "qty": 2
    },
    {
      "kind": "salida",
      "date": "2026-07-31",
      "partNumber": "VF06-1/2",
      "description": "valvula control de flujo",
      "qty": 1
    },
    {
      "kind": "salida",
      "date": "2026-07-31",
      "partNumber": "—",
      "description": "guías puente balancines jinan",
      "qty": 1
    },
    {
      "kind": "entrada",
      "date": "2026-08-03",
      "partNumber": "—",
      "description": "empaques de tapa válvulas j320",
      "qty": 60
    },
    {
      "kind": "entrada",
      "date": "2026-08-03",
      "partNumber": "—",
      "description": "bujías jinan en cco",
      "qty": 8
    },
    {
      "kind": "entrada",
      "date": "2026-08-03",
      "partNumber": "1232128",
      "description": "bomba grundfos",
      "qty": 1
    },
    {
      "kind": "salida",
      "date": "2026-08-06",
      "partNumber": "1227732",
      "description": "filtro interno de aire j420",
      "qty": 3
    },
    {
      "kind": "salida",
      "date": "2026-08-06",
      "partNumber": "245488",
      "description": "filtro aceite j420",
      "qty": 1
    },
    {
      "kind": "salida",
      "date": "2026-08-06",
      "partNumber": "—",
      "description": "filtro gas entrada",
      "qty": 1
    },
    {
      "kind": "salida",
      "date": "2026-08-06",
      "partNumber": "—",
      "description": "par de guantes",
      "qty": 1
    },
    {
      "kind": "salida",
      "date": "2026-08-06",
      "partNumber": "1232128",
      "description": "bomba grndfus",
      "qty": 1
    },
    {
      "kind": "salida",
      "date": "2026-08-10",
      "partNumber": "12VB0103",
      "description": "anillo cobre asiento culata jinan",
      "qty": 5
    },
    {
      "kind": "salida",
      "date": "2026-08-10",
      "partNumber": "—",
      "description": "filtro gas jinan",
      "qty": 2
    },
    {
      "kind": "salida",
      "date": "2026-08-10",
      "partNumber": "12VB1810B",
      "description": "filtro aceite jinan",
      "qty": 5
    },
    {
      "kind": "salida",
      "date": "2026-08-10",
      "partNumber": "2770303",
      "description": "gasket asiento sleeve jinan",
      "qty": 5
    },
    {
      "kind": "salida",
      "date": "2026-08-10",
      "partNumber": "P01847",
      "description": "junta múltiple de admisión jinan",
      "qty": 6
    },
    {
      "kind": "salida",
      "date": "2026-08-10",
      "partNumber": "—",
      "description": "sellos tipo grommet jinan",
      "qty": 24
    },
    {
      "kind": "salida",
      "date": "2026-08-10",
      "partNumber": "12VB2407",
      "description": "gasket tubería agua jinan",
      "qty": 7
    },
    {
      "kind": "salida",
      "date": "2026-08-10",
      "partNumber": "—",
      "description": "desengrasante industrial",
      "qty": 1
    }
  ]
};
