/** Catálogos y tipos del módulo Optimización de Planes de Mantenimiento (MSO). */

export const MAINTENANCE_STRATEGIES = [
  "Correctivo",
  "Preventivo",
  "Predictivo",
  "Basado en Condición",
  "RCM",
  "Run To Failure",
] as const;

export type MaintenanceStrategy = (typeof MAINTENANCE_STRATEGIES)[number];

export const CRITICALITY_LEVELS = ["Muy Alta", "Alta", "Media", "Baja"] as const;
export type CriticalityLevel = (typeof CRITICALITY_LEVELS)[number];

export const EQUIPMENT_TYPES = [
  "Motor",
  "Generador",
  "Interruptor",
  "Radiador",
  "Intercooler",
  "MRU",
  "Gobernador",
  "AVR",
  "Transformador",
] as const;

export type EquipmentType = (typeof EQUIPMENT_TYPES)[number];

export type OptimizationStatus =
  | "Pendiente análisis"
  | "Requiere optimización"
  | "En aprobación"
  | "Implementado"
  | "Validado";

export type PlanHealthBand = "Excelente" | "Aceptable" | "Requiere optimización";

export type EvaluationLabel = "Adecuado" | "Requiere ajuste" | "Deficiente";

export type RecommendationPriority = "Crítica" | "Alta" | "Media" | "Baja";

export type RecommendationStatus = "Abierta" | "En curso" | "Implementada" | "Descartada";

export type ExpectedBenefits = {
  mtbfPct: number;
  availabilityPct: number;
  mttrPct: number;
  costPct: number;
  failuresPct: number;
};

export type MaintenanceRecommendation = {
  id: string;
  planId: string;
  recommendation: string;
  priority: RecommendationPriority;
  expectedBenefit: string;
  /** Ahorro estimado en costo de mantenimiento (%). */
  estimatedSavingsPct: number;
  implementationCost: number;
  responsible: string;
  status: RecommendationStatus;
  createdAt: string;
  autoGenerated: boolean;
  trigger?: string;
};

export type MaintenanceOptimizationPlan = {
  id: string;
  assetId: string;
  assetName: string;
  equipmentType: EquipmentType;
  manufacturer: string;
  criticality: CriticalityLevel;
  currentStrategy: MaintenanceStrategy;
  currentFrequency: string;
  recommendedStrategy: MaintenanceStrategy;
  recommendedFrequency: string;
  optimizationStatus: OptimizationStatus;
  justification: string;
  /** Maintenance Plan Health Index 0–100 */
  mphi: number;
  healthBand: PlanHealthBand;
  evaluation: EvaluationLabel;
  expectedBenefit: string;
  benefits: ExpectedBenefits;
  operatingHours: number;
  availabilityPct: number;
  mtbfHours: number | null;
  mttrHours: number | null;
  failures: number;
  maintenanceCostUsd: number;
  outageHours: number;
  impactIndex: number;
  linkedRcaIds: string[];
  linkedPlanIds: string[];
  linkedEventHints: string[];
  recommendations: MaintenanceRecommendation[];
  createdAt: string;
  updatedAt: string;
};

export const CRITICALITY_COLOR: Record<CriticalityLevel, string> = {
  "Muy Alta": "#ef4444",
  Alta: "#f97316",
  Media: "#3b82f6",
  Baja: "#94a3b8",
};

export const HEALTH_COLOR: Record<PlanHealthBand, string> = {
  Excelente: "#16a34a",
  Aceptable: "#ca8a04",
  "Requiere optimización": "#dc2626",
};

export const EVAL_COLOR: Record<EvaluationLabel, string> = {
  Adecuado: "#16a34a",
  "Requiere ajuste": "#ca8a04",
  Deficiente: "#dc2626",
};

export function healthBandFromMphi(mphi: number): PlanHealthBand {
  if (mphi >= 80) return "Excelente";
  if (mphi >= 60) return "Aceptable";
  return "Requiere optimización";
}

export function evaluationFromMphi(mphi: number): EvaluationLabel {
  if (mphi >= 80) return "Adecuado";
  if (mphi >= 60) return "Requiere ajuste";
  return "Deficiente";
}

/**
 * MPHI (0–100): criticidad, disponibilidad, reincidencia, MTBF relativo, MTTR y cumplimiento.
 * Diferenciador frente a CMMS tradicionales.
 */
export function computeMphi(input: {
  criticality: CriticalityLevel;
  availabilityPct: number;
  failures: number;
  mtbfHours: number | null;
  mttrHours: number | null;
  impactIndex: number;
}): number {
  const critScore =
    input.criticality === "Muy Alta"
      ? 55
      : input.criticality === "Alta"
        ? 70
        : input.criticality === "Media"
          ? 85
          : 95;

  const availScore = Math.max(0, Math.min(100, ((input.availabilityPct - 90) / 10) * 100));
  const failScore = Math.max(0, 100 - input.failures * 18);
  const mtbfScore =
    input.mtbfHours == null || input.mtbfHours <= 0
      ? 95
      : Math.max(0, Math.min(100, (input.mtbfHours / 720) * 100));
  const mttrScore =
    input.mttrHours == null
      ? 90
      : Math.max(0, 100 - Math.min(100, input.mttrHours * 12));
  const impactScore = Math.max(0, 100 - input.impactIndex * 10);

  const raw =
    0.2 * critScore +
    0.25 * availScore +
    0.2 * failScore +
    0.15 * mtbfScore +
    0.1 * mttrScore +
    0.1 * impactScore;

  return Math.round(Math.max(0, Math.min(100, raw)));
}
